// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"oa-nsdiy/backend/ent/apitoken"
	"oa-nsdiy/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ApiTokenCreate is the builder for creating a ApiToken entity.
type ApiTokenCreate struct {
	config
	mutation *ApiTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ApiTokenCreate) SetCreatedAt(v time.Time) *ApiTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableCreatedAt(v *time.Time) *ApiTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ApiTokenCreate) SetUpdatedAt(v time.Time) *ApiTokenCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableUpdatedAt(v *time.Time) *ApiTokenCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ApiTokenCreate) SetUserID(v int) *ApiTokenCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ApiTokenCreate) SetName(v string) *ApiTokenCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *ApiTokenCreate) SetTokenHash(v string) *ApiTokenCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetTokenPrefix sets the "token_prefix" field.
func (_c *ApiTokenCreate) SetTokenPrefix(v string) *ApiTokenCreate {
	_c.mutation.SetTokenPrefix(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ApiTokenCreate) SetStatus(v string) *ApiTokenCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableStatus(v *string) *ApiTokenCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ApiTokenCreate) SetExpiresAt(v time.Time) *ApiTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableExpiresAt(v *time.Time) *ApiTokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *ApiTokenCreate) SetLastUsedAt(v time.Time) *ApiTokenCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableLastUsedAt(v *time.Time) *ApiTokenCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetUsageCount sets the "usage_count" field.
func (_c *ApiTokenCreate) SetUsageCount(v int) *ApiTokenCreate {
	_c.mutation.SetUsageCount(v)
	return _c
}

// SetNillableUsageCount sets the "usage_count" field if the given value is not nil.
func (_c *ApiTokenCreate) SetNillableUsageCount(v *int) *ApiTokenCreate {
	if v != nil {
		_c.SetUsageCount(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ApiTokenCreate) SetUser(v *User) *ApiTokenCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ApiTokenMutation object of the builder.
func (_c *ApiTokenCreate) Mutation() *ApiTokenMutation {
	return _c.mutation
}

// Save creates the ApiToken in the database.
func (_c *ApiTokenCreate) Save(ctx context.Context) (*ApiToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ApiTokenCreate) SaveX(ctx context.Context) *ApiToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApiTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApiTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ApiTokenCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apitoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apitoken.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := apitoken.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UsageCount(); !ok {
		v := apitoken.DefaultUsageCount
		_c.mutation.SetUsageCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ApiTokenCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ApiToken.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ApiToken.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ApiToken.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := apitoken.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ApiToken.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ApiToken.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := apitoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ApiToken.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "ApiToken.token_hash"`)}
	}
	if v, ok := _c.mutation.TokenHash(); ok {
		if err := apitoken.TokenHashValidator(v); err != nil {
			return &ValidationError{Name: "token_hash", err: fmt.Errorf(`ent: validator failed for field "ApiToken.token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenPrefix(); !ok {
		return &ValidationError{Name: "token_prefix", err: errors.New(`ent: missing required field "ApiToken.token_prefix"`)}
	}
	if v, ok := _c.mutation.TokenPrefix(); ok {
		if err := apitoken.TokenPrefixValidator(v); err != nil {
			return &ValidationError{Name: "token_prefix", err: fmt.Errorf(`ent: validator failed for field "ApiToken.token_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ApiToken.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := apitoken.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ApiToken.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsageCount(); !ok {
		return &ValidationError{Name: "usage_count", err: errors.New(`ent: missing required field "ApiToken.usage_count"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ApiToken.user"`)}
	}
	return nil
}

func (_c *ApiTokenCreate) sqlSave(ctx context.Context) (*ApiToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ApiTokenCreate) createSpec() (*ApiToken, *sqlgraph.CreateSpec) {
	var (
		_node = &ApiToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apitoken.Table, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apitoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apitoken.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(apitoken.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.TokenPrefix(); ok {
		_spec.SetField(apitoken.FieldTokenPrefix, field.TypeString, value)
		_node.TokenPrefix = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(apitoken.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(apitoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(apitoken.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = value
	}
	if value, ok := _c.mutation.UsageCount(); ok {
		_spec.SetField(apitoken.FieldUsageCount, field.TypeInt, value)
		_node.UsageCount = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.UserTable,
			Columns: []string{apitoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ApiToken.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ApiTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ApiTokenCreate) OnConflict(opts ...sql.ConflictOption) *ApiTokenUpsertOne {
	_c.conflict = opts
	return &ApiTokenUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ApiToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ApiTokenCreate) OnConflictColumns(columns ...string) *ApiTokenUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ApiTokenUpsertOne{
		create: _c,
	}
}

type (
	// ApiTokenUpsertOne is the builder for "upsert"-ing
	//  one ApiToken node.
	ApiTokenUpsertOne struct {
		create *ApiTokenCreate
	}

	// ApiTokenUpsert is the "OnConflict" setter.
	ApiTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ApiTokenUpsert) SetUpdatedAt(v time.Time) *ApiTokenUpsert {
	u.Set(apitoken.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ApiTokenUpsert) UpdateUpdatedAt() *ApiTokenUpsert {
	u.SetExcluded(apitoken.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ApiTokenUpsert) SetUserID(v int) *ApiTokenUpsert {
	u.Set(apitoken.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ApiTokenUpsert) UpdateUserID() *ApiTokenUpsert {
	u.SetExcluded(apitoken.FieldUserID)
	return u
}

// SetName sets the "name" field.
func (u *ApiTokenUpsert) SetName(v string) *ApiTokenUpsert {
	u.Set(apitoken.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ApiTokenUpsert) UpdateName() *ApiTokenUpsert {
	u.SetExcluded(apitoken.FieldName)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *ApiTokenUpsert) SetTokenHash(v string) *ApiTokenUpsert {
	u.Set(apitoken.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *ApiTokenUpsert) UpdateTokenHash() *ApiTokenUpsert {
	u.SetExcluded(apitoken.FieldTokenHash)
	return u
}

// SetTokenPrefix sets the "token_prefix" field.
func (u *ApiTokenUpsert) SetTokenPrefix(v string) *ApiTokenUpsert {
	u.Set(apitoken.FieldTokenPrefix, v)
	return u
}

// UpdateTokenPrefix sets the "token_prefix" field to the value that was provided on create.
func (u *ApiTokenUpsert) UpdateTokenPrefix() *ApiTokenUpsert {
	u.SetExcluded(apitoken.FieldTokenPrefix)
	return u
}

// SetStatus sets the "status" field.
func (u *ApiTokenUpsert) SetStatus(v string) *ApiTokenUpsert {
	u.Set(apitoken.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ApiTokenUpsert) UpdateStatus() *ApiTokenUpsert {
	u.SetExcluded(apitoken.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ApiTokenUpsert) SetExpiresAt(v time.Time) *ApiTokenUpsert {
	u.Set(apitoken.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ApiTokenUpsert) UpdateExpiresAt() *ApiTokenUpsert {
	u.SetExcluded(apitoken.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ApiTokenUpsert) ClearExpiresAt() *ApiTokenUpsert {
	u.SetNull(apitoken.FieldExpiresAt)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *ApiTokenUpsert) SetLastUsedAt(v time.Time) *ApiTokenUpsert {
	u.Set(apitoken.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *ApiTokenUpsert) UpdateLastUsedAt() *ApiTokenUpsert {
	u.SetExcluded(apitoken.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *ApiTokenUpsert) ClearLastUsedAt() *ApiTokenUpsert {
	u.SetNull(apitoken.FieldLastUsedAt)
	return u
}

// SetUsageCount sets the "usage_count" field.
func (u *ApiTokenUpsert) SetUsageCount(v int) *ApiTokenUpsert {
	u.Set(apitoken.FieldUsageCount, v)
	return u
}

// UpdateUsageCount sets the "usage_count" field to the value that was provided on create.
func (u *ApiTokenUpsert) UpdateUsageCount() *ApiTokenUpsert {
	u.SetExcluded(apitoken.FieldUsageCount)
	return u
}

// AddUsageCount adds v to the "usage_count" field.
func (u *ApiTokenUpsert) AddUsageCount(v int) *ApiTokenUpsert {
	u.Add(apitoken.FieldUsageCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ApiToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ApiTokenUpsertOne) UpdateNewValues() *ApiTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apitoken.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ApiToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ApiTokenUpsertOne) Ignore() *ApiTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ApiTokenUpsertOne) DoNothing() *ApiTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ApiTokenCreate.OnConflict
// documentation for more info.
func (u *ApiTokenUpsertOne) Update(set func(*ApiTokenUpsert)) *ApiTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ApiTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ApiTokenUpsertOne) SetUpdatedAt(v time.Time) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ApiTokenUpsertOne) UpdateUpdatedAt() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ApiTokenUpsertOne) SetUserID(v int) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ApiTokenUpsertOne) UpdateUserID() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *ApiTokenUpsertOne) SetName(v string) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ApiTokenUpsertOne) UpdateName() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateName()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *ApiTokenUpsertOne) SetTokenHash(v string) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *ApiTokenUpsertOne) UpdateTokenHash() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateTokenHash()
	})
}

// SetTokenPrefix sets the "token_prefix" field.
func (u *ApiTokenUpsertOne) SetTokenPrefix(v string) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetTokenPrefix(v)
	})
}

// UpdateTokenPrefix sets the "token_prefix" field to the value that was provided on create.
func (u *ApiTokenUpsertOne) UpdateTokenPrefix() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateTokenPrefix()
	})
}

// SetStatus sets the "status" field.
func (u *ApiTokenUpsertOne) SetStatus(v string) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ApiTokenUpsertOne) UpdateStatus() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ApiTokenUpsertOne) SetExpiresAt(v time.Time) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ApiTokenUpsertOne) UpdateExpiresAt() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ApiTokenUpsertOne) ClearExpiresAt() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *ApiTokenUpsertOne) SetLastUsedAt(v time.Time) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *ApiTokenUpsertOne) UpdateLastUsedAt() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *ApiTokenUpsertOne) ClearLastUsedAt() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetUsageCount sets the "usage_count" field.
func (u *ApiTokenUpsertOne) SetUsageCount(v int) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetUsageCount(v)
	})
}

// AddUsageCount adds v to the "usage_count" field.
func (u *ApiTokenUpsertOne) AddUsageCount(v int) *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.AddUsageCount(v)
	})
}

// UpdateUsageCount sets the "usage_count" field to the value that was provided on create.
func (u *ApiTokenUpsertOne) UpdateUsageCount() *ApiTokenUpsertOne {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateUsageCount()
	})
}

// Exec executes the query.
func (u *ApiTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ApiTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ApiTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ApiTokenUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ApiTokenUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ApiTokenCreateBulk is the builder for creating many ApiToken entities in bulk.
type ApiTokenCreateBulk struct {
	config
	err      error
	builders []*ApiTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the ApiToken entities in the database.
func (_c *ApiTokenCreateBulk) Save(ctx context.Context) ([]*ApiToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ApiToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ApiTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ApiTokenCreateBulk) SaveX(ctx context.Context) []*ApiToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ApiTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ApiTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ApiToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ApiTokenUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ApiTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *ApiTokenUpsertBulk {
	_c.conflict = opts
	return &ApiTokenUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ApiToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ApiTokenCreateBulk) OnConflictColumns(columns ...string) *ApiTokenUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ApiTokenUpsertBulk{
		create: _c,
	}
}

// ApiTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of ApiToken nodes.
type ApiTokenUpsertBulk struct {
	create *ApiTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ApiToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ApiTokenUpsertBulk) UpdateNewValues() *ApiTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apitoken.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ApiToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ApiTokenUpsertBulk) Ignore() *ApiTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ApiTokenUpsertBulk) DoNothing() *ApiTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ApiTokenCreateBulk.OnConflict
// documentation for more info.
func (u *ApiTokenUpsertBulk) Update(set func(*ApiTokenUpsert)) *ApiTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ApiTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ApiTokenUpsertBulk) SetUpdatedAt(v time.Time) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ApiTokenUpsertBulk) UpdateUpdatedAt() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ApiTokenUpsertBulk) SetUserID(v int) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ApiTokenUpsertBulk) UpdateUserID() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *ApiTokenUpsertBulk) SetName(v string) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ApiTokenUpsertBulk) UpdateName() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateName()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *ApiTokenUpsertBulk) SetTokenHash(v string) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *ApiTokenUpsertBulk) UpdateTokenHash() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateTokenHash()
	})
}

// SetTokenPrefix sets the "token_prefix" field.
func (u *ApiTokenUpsertBulk) SetTokenPrefix(v string) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetTokenPrefix(v)
	})
}

// UpdateTokenPrefix sets the "token_prefix" field to the value that was provided on create.
func (u *ApiTokenUpsertBulk) UpdateTokenPrefix() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateTokenPrefix()
	})
}

// SetStatus sets the "status" field.
func (u *ApiTokenUpsertBulk) SetStatus(v string) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ApiTokenUpsertBulk) UpdateStatus() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ApiTokenUpsertBulk) SetExpiresAt(v time.Time) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ApiTokenUpsertBulk) UpdateExpiresAt() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ApiTokenUpsertBulk) ClearExpiresAt() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *ApiTokenUpsertBulk) SetLastUsedAt(v time.Time) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *ApiTokenUpsertBulk) UpdateLastUsedAt() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *ApiTokenUpsertBulk) ClearLastUsedAt() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetUsageCount sets the "usage_count" field.
func (u *ApiTokenUpsertBulk) SetUsageCount(v int) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.SetUsageCount(v)
	})
}

// AddUsageCount adds v to the "usage_count" field.
func (u *ApiTokenUpsertBulk) AddUsageCount(v int) *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.AddUsageCount(v)
	})
}

// UpdateUsageCount sets the "usage_count" field to the value that was provided on create.
func (u *ApiTokenUpsertBulk) UpdateUsageCount() *ApiTokenUpsertBulk {
	return u.Update(func(s *ApiTokenUpsert) {
		s.UpdateUsageCount()
	})
}

// Exec executes the query.
func (u *ApiTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ApiTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ApiTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ApiTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
