// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"oa-nsdiy/backend/ent/article"
	"oa-nsdiy/backend/ent/articleversion"
	"oa-nsdiy/backend/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ArticleVersion is the model entity for the ArticleVersion schema.
type ArticleVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ArticleID holds the value of the "article_id" field.
	ArticleID int `json:"article_id,omitempty"`
	// VersionNo holds the value of the "version_no" field.
	VersionNo int `json:"version_no,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// CoverDescription holds the value of the "cover_description" field.
	CoverDescription string `json:"cover_description,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// EditorID holds the value of the "editor_id" field.
	EditorID int `json:"editor_id,omitempty"`
	// EditReason holds the value of the "edit_reason" field.
	EditReason string `json:"edit_reason,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArticleVersionQuery when eager-loading is set.
	Edges        ArticleVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ArticleVersionEdges holds the relations/edges for other nodes in the graph.
type ArticleVersionEdges struct {
	// Article holds the value of the article edge.
	Article *Article `json:"article,omitempty"`
	// Editor holds the value of the editor edge.
	Editor *User `json:"editor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ArticleOrErr returns the Article value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArticleVersionEdges) ArticleOrErr() (*Article, error) {
	if e.Article != nil {
		return e.Article, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: article.Label}
	}
	return nil, &NotLoadedError{edge: "article"}
}

// EditorOrErr returns the Editor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArticleVersionEdges) EditorOrErr() (*User, error) {
	if e.Editor != nil {
		return e.Editor, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "editor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArticleVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case articleversion.FieldID, articleversion.FieldArticleID, articleversion.FieldVersionNo, articleversion.FieldEditorID:
			values[i] = new(sql.NullInt64)
		case articleversion.FieldTitle, articleversion.FieldContent, articleversion.FieldCoverDescription, articleversion.FieldSummary, articleversion.FieldStatus, articleversion.FieldEditReason:
			values[i] = new(sql.NullString)
		case articleversion.FieldCreatedAt, articleversion.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArticleVersion fields.
func (_m *ArticleVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case articleversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case articleversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case articleversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case articleversion.FieldArticleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field article_id", values[i])
			} else if value.Valid {
				_m.ArticleID = int(value.Int64)
			}
		case articleversion.FieldVersionNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version_no", values[i])
			} else if value.Valid {
				_m.VersionNo = int(value.Int64)
			}
		case articleversion.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case articleversion.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case articleversion.FieldCoverDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_description", values[i])
			} else if value.Valid {
				_m.CoverDescription = value.String
			}
		case articleversion.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case articleversion.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case articleversion.FieldEditorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field editor_id", values[i])
			} else if value.Valid {
				_m.EditorID = int(value.Int64)
			}
		case articleversion.FieldEditReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field edit_reason", values[i])
			} else if value.Valid {
				_m.EditReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ArticleVersion.
// This includes values selected through modifiers, order, etc.
func (_m *ArticleVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryArticle queries the "article" edge of the ArticleVersion entity.
func (_m *ArticleVersion) QueryArticle() *ArticleQuery {
	return NewArticleVersionClient(_m.config).QueryArticle(_m)
}

// QueryEditor queries the "editor" edge of the ArticleVersion entity.
func (_m *ArticleVersion) QueryEditor() *UserQuery {
	return NewArticleVersionClient(_m.config).QueryEditor(_m)
}

// Update returns a builder for updating this ArticleVersion.
// Note that you need to call ArticleVersion.Unwrap() before calling this method if this ArticleVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ArticleVersion) Update() *ArticleVersionUpdateOne {
	return NewArticleVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ArticleVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ArticleVersion) Unwrap() *ArticleVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArticleVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ArticleVersion) String() string {
	var builder strings.Builder
	builder.WriteString("ArticleVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("article_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ArticleID))
	builder.WriteString(", ")
	builder.WriteString("version_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.VersionNo))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("cover_description=")
	builder.WriteString(_m.CoverDescription)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("editor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EditorID))
	builder.WriteString(", ")
	builder.WriteString("edit_reason=")
	builder.WriteString(_m.EditReason)
	builder.WriteByte(')')
	return builder.String()
}

// ArticleVersions is a parsable slice of ArticleVersion.
type ArticleVersions []*ArticleVersion
