// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"oa-nsdiy/backend/ent/article"
	"oa-nsdiy/backend/ent/articleversion"
	"oa-nsdiy/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticleVersionCreate is the builder for creating a ArticleVersion entity.
type ArticleVersionCreate struct {
	config
	mutation *ArticleVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ArticleVersionCreate) SetCreatedAt(v time.Time) *ArticleVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ArticleVersionCreate) SetNillableCreatedAt(v *time.Time) *ArticleVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ArticleVersionCreate) SetUpdatedAt(v time.Time) *ArticleVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ArticleVersionCreate) SetNillableUpdatedAt(v *time.Time) *ArticleVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetArticleID sets the "article_id" field.
func (_c *ArticleVersionCreate) SetArticleID(v int) *ArticleVersionCreate {
	_c.mutation.SetArticleID(v)
	return _c
}

// SetVersionNo sets the "version_no" field.
func (_c *ArticleVersionCreate) SetVersionNo(v int) *ArticleVersionCreate {
	_c.mutation.SetVersionNo(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ArticleVersionCreate) SetTitle(v string) *ArticleVersionCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ArticleVersionCreate) SetContent(v string) *ArticleVersionCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *ArticleVersionCreate) SetNillableContent(v *string) *ArticleVersionCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetCoverDescription sets the "cover_description" field.
func (_c *ArticleVersionCreate) SetCoverDescription(v string) *ArticleVersionCreate {
	_c.mutation.SetCoverDescription(v)
	return _c
}

// SetNillableCoverDescription sets the "cover_description" field if the given value is not nil.
func (_c *ArticleVersionCreate) SetNillableCoverDescription(v *string) *ArticleVersionCreate {
	if v != nil {
		_c.SetCoverDescription(*v)
	}
	return _c
}

// SetSummary sets the "summary" field.
func (_c *ArticleVersionCreate) SetSummary(v string) *ArticleVersionCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *ArticleVersionCreate) SetNillableSummary(v *string) *ArticleVersionCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ArticleVersionCreate) SetStatus(v string) *ArticleVersionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetEditorID sets the "editor_id" field.
func (_c *ArticleVersionCreate) SetEditorID(v int) *ArticleVersionCreate {
	_c.mutation.SetEditorID(v)
	return _c
}

// SetNillableEditorID sets the "editor_id" field if the given value is not nil.
func (_c *ArticleVersionCreate) SetNillableEditorID(v *int) *ArticleVersionCreate {
	if v != nil {
		_c.SetEditorID(*v)
	}
	return _c
}

// SetEditReason sets the "edit_reason" field.
func (_c *ArticleVersionCreate) SetEditReason(v string) *ArticleVersionCreate {
	_c.mutation.SetEditReason(v)
	return _c
}

// SetNillableEditReason sets the "edit_reason" field if the given value is not nil.
func (_c *ArticleVersionCreate) SetNillableEditReason(v *string) *ArticleVersionCreate {
	if v != nil {
		_c.SetEditReason(*v)
	}
	return _c
}

// SetArticle sets the "article" edge to the Article entity.
func (_c *ArticleVersionCreate) SetArticle(v *Article) *ArticleVersionCreate {
	return _c.SetArticleID(v.ID)
}

// SetEditor sets the "editor" edge to the User entity.
func (_c *ArticleVersionCreate) SetEditor(v *User) *ArticleVersionCreate {
	return _c.SetEditorID(v.ID)
}

// Mutation returns the ArticleVersionMutation object of the builder.
func (_c *ArticleVersionCreate) Mutation() *ArticleVersionMutation {
	return _c.mutation
}

// Save creates the ArticleVersion in the database.
func (_c *ArticleVersionCreate) Save(ctx context.Context) (*ArticleVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArticleVersionCreate) SaveX(ctx context.Context) *ArticleVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArticleVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArticleVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ArticleVersionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := articleversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := articleversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArticleVersionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ArticleVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ArticleVersion.updated_at"`)}
	}
	if _, ok := _c.mutation.ArticleID(); !ok {
		return &ValidationError{Name: "article_id", err: errors.New(`ent: missing required field "ArticleVersion.article_id"`)}
	}
	if v, ok := _c.mutation.ArticleID(); ok {
		if err := articleversion.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.article_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VersionNo(); !ok {
		return &ValidationError{Name: "version_no", err: errors.New(`ent: missing required field "ArticleVersion.version_no"`)}
	}
	if v, ok := _c.mutation.VersionNo(); ok {
		if err := articleversion.VersionNoValidator(v); err != nil {
			return &ValidationError{Name: "version_no", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.version_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ArticleVersion.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := articleversion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CoverDescription(); ok {
		if err := articleversion.CoverDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "cover_description", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.cover_description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := articleversion.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.summary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ArticleVersion.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := articleversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EditReason(); ok {
		if err := articleversion.EditReasonValidator(v); err != nil {
			return &ValidationError{Name: "edit_reason", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.edit_reason": %w`, err)}
		}
	}
	if len(_c.mutation.ArticleIDs()) == 0 {
		return &ValidationError{Name: "article", err: errors.New(`ent: missing required edge "ArticleVersion.article"`)}
	}
	return nil
}

func (_c *ArticleVersionCreate) sqlSave(ctx context.Context) (*ArticleVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArticleVersionCreate) createSpec() (*ArticleVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ArticleVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(articleversion.Table, sqlgraph.NewFieldSpec(articleversion.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(articleversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(articleversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.VersionNo(); ok {
		_spec.SetField(articleversion.FieldVersionNo, field.TypeInt, value)
		_node.VersionNo = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(articleversion.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(articleversion.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CoverDescription(); ok {
		_spec.SetField(articleversion.FieldCoverDescription, field.TypeString, value)
		_node.CoverDescription = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(articleversion.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(articleversion.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EditReason(); ok {
		_spec.SetField(articleversion.FieldEditReason, field.TypeString, value)
		_node.EditReason = value
	}
	if nodes := _c.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.ArticleTable,
			Columns: []string{articleversion.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ArticleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EditorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.EditorTable,
			Columns: []string{articleversion.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EditorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArticleVersion.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArticleVersionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ArticleVersionCreate) OnConflict(opts ...sql.ConflictOption) *ArticleVersionUpsertOne {
	_c.conflict = opts
	return &ArticleVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArticleVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ArticleVersionCreate) OnConflictColumns(columns ...string) *ArticleVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ArticleVersionUpsertOne{
		create: _c,
	}
}

type (
	// ArticleVersionUpsertOne is the builder for "upsert"-ing
	//  one ArticleVersion node.
	ArticleVersionUpsertOne struct {
		create *ArticleVersionCreate
	}

	// ArticleVersionUpsert is the "OnConflict" setter.
	ArticleVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ArticleVersionUpsert) SetUpdatedAt(v time.Time) *ArticleVersionUpsert {
	u.Set(articleversion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateUpdatedAt() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldUpdatedAt)
	return u
}

// SetArticleID sets the "article_id" field.
func (u *ArticleVersionUpsert) SetArticleID(v int) *ArticleVersionUpsert {
	u.Set(articleversion.FieldArticleID, v)
	return u
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateArticleID() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldArticleID)
	return u
}

// SetVersionNo sets the "version_no" field.
func (u *ArticleVersionUpsert) SetVersionNo(v int) *ArticleVersionUpsert {
	u.Set(articleversion.FieldVersionNo, v)
	return u
}

// UpdateVersionNo sets the "version_no" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateVersionNo() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldVersionNo)
	return u
}

// AddVersionNo adds v to the "version_no" field.
func (u *ArticleVersionUpsert) AddVersionNo(v int) *ArticleVersionUpsert {
	u.Add(articleversion.FieldVersionNo, v)
	return u
}

// SetTitle sets the "title" field.
func (u *ArticleVersionUpsert) SetTitle(v string) *ArticleVersionUpsert {
	u.Set(articleversion.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateTitle() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *ArticleVersionUpsert) SetContent(v string) *ArticleVersionUpsert {
	u.Set(articleversion.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateContent() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *ArticleVersionUpsert) ClearContent() *ArticleVersionUpsert {
	u.SetNull(articleversion.FieldContent)
	return u
}

// SetCoverDescription sets the "cover_description" field.
func (u *ArticleVersionUpsert) SetCoverDescription(v string) *ArticleVersionUpsert {
	u.Set(articleversion.FieldCoverDescription, v)
	return u
}

// UpdateCoverDescription sets the "cover_description" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateCoverDescription() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldCoverDescription)
	return u
}

// ClearCoverDescription clears the value of the "cover_description" field.
func (u *ArticleVersionUpsert) ClearCoverDescription() *ArticleVersionUpsert {
	u.SetNull(articleversion.FieldCoverDescription)
	return u
}

// SetSummary sets the "summary" field.
func (u *ArticleVersionUpsert) SetSummary(v string) *ArticleVersionUpsert {
	u.Set(articleversion.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateSummary() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldSummary)
	return u
}

// ClearSummary clears the value of the "summary" field.
func (u *ArticleVersionUpsert) ClearSummary() *ArticleVersionUpsert {
	u.SetNull(articleversion.FieldSummary)
	return u
}

// SetStatus sets the "status" field.
func (u *ArticleVersionUpsert) SetStatus(v string) *ArticleVersionUpsert {
	u.Set(articleversion.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateStatus() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldStatus)
	return u
}

// SetEditorID sets the "editor_id" field.
func (u *ArticleVersionUpsert) SetEditorID(v int) *ArticleVersionUpsert {
	u.Set(articleversion.FieldEditorID, v)
	return u
}

// UpdateEditorID sets the "editor_id" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateEditorID() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldEditorID)
	return u
}

// ClearEditorID clears the value of the "editor_id" field.
func (u *ArticleVersionUpsert) ClearEditorID() *ArticleVersionUpsert {
	u.SetNull(articleversion.FieldEditorID)
	return u
}

// SetEditReason sets the "edit_reason" field.
func (u *ArticleVersionUpsert) SetEditReason(v string) *ArticleVersionUpsert {
	u.Set(articleversion.FieldEditReason, v)
	return u
}

// UpdateEditReason sets the "edit_reason" field to the value that was provided on create.
func (u *ArticleVersionUpsert) UpdateEditReason() *ArticleVersionUpsert {
	u.SetExcluded(articleversion.FieldEditReason)
	return u
}

// ClearEditReason clears the value of the "edit_reason" field.
func (u *ArticleVersionUpsert) ClearEditReason() *ArticleVersionUpsert {
	u.SetNull(articleversion.FieldEditReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ArticleVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ArticleVersionUpsertOne) UpdateNewValues() *ArticleVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(articleversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ArticleVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ArticleVersionUpsertOne) Ignore() *ArticleVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArticleVersionUpsertOne) DoNothing() *ArticleVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArticleVersionCreate.OnConflict
// documentation for more info.
func (u *ArticleVersionUpsertOne) Update(set func(*ArticleVersionUpsert)) *ArticleVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArticleVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArticleVersionUpsertOne) SetUpdatedAt(v time.Time) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateUpdatedAt() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetArticleID sets the "article_id" field.
func (u *ArticleVersionUpsertOne) SetArticleID(v int) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetArticleID(v)
	})
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateArticleID() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateArticleID()
	})
}

// SetVersionNo sets the "version_no" field.
func (u *ArticleVersionUpsertOne) SetVersionNo(v int) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetVersionNo(v)
	})
}

// AddVersionNo adds v to the "version_no" field.
func (u *ArticleVersionUpsertOne) AddVersionNo(v int) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.AddVersionNo(v)
	})
}

// UpdateVersionNo sets the "version_no" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateVersionNo() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateVersionNo()
	})
}

// SetTitle sets the "title" field.
func (u *ArticleVersionUpsertOne) SetTitle(v string) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateTitle() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *ArticleVersionUpsertOne) SetContent(v string) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateContent() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *ArticleVersionUpsertOne) ClearContent() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearContent()
	})
}

// SetCoverDescription sets the "cover_description" field.
func (u *ArticleVersionUpsertOne) SetCoverDescription(v string) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetCoverDescription(v)
	})
}

// UpdateCoverDescription sets the "cover_description" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateCoverDescription() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateCoverDescription()
	})
}

// ClearCoverDescription clears the value of the "cover_description" field.
func (u *ArticleVersionUpsertOne) ClearCoverDescription() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearCoverDescription()
	})
}

// SetSummary sets the "summary" field.
func (u *ArticleVersionUpsertOne) SetSummary(v string) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateSummary() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *ArticleVersionUpsertOne) ClearSummary() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearSummary()
	})
}

// SetStatus sets the "status" field.
func (u *ArticleVersionUpsertOne) SetStatus(v string) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateStatus() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetEditorID sets the "editor_id" field.
func (u *ArticleVersionUpsertOne) SetEditorID(v int) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetEditorID(v)
	})
}

// UpdateEditorID sets the "editor_id" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateEditorID() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateEditorID()
	})
}

// ClearEditorID clears the value of the "editor_id" field.
func (u *ArticleVersionUpsertOne) ClearEditorID() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearEditorID()
	})
}

// SetEditReason sets the "edit_reason" field.
func (u *ArticleVersionUpsertOne) SetEditReason(v string) *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetEditReason(v)
	})
}

// UpdateEditReason sets the "edit_reason" field to the value that was provided on create.
func (u *ArticleVersionUpsertOne) UpdateEditReason() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateEditReason()
	})
}

// ClearEditReason clears the value of the "edit_reason" field.
func (u *ArticleVersionUpsertOne) ClearEditReason() *ArticleVersionUpsertOne {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearEditReason()
	})
}

// Exec executes the query.
func (u *ArticleVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArticleVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArticleVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ArticleVersionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ArticleVersionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ArticleVersionCreateBulk is the builder for creating many ArticleVersion entities in bulk.
type ArticleVersionCreateBulk struct {
	config
	err      error
	builders []*ArticleVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the ArticleVersion entities in the database.
func (_c *ArticleVersionCreateBulk) Save(ctx context.Context) ([]*ArticleVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ArticleVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArticleVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArticleVersionCreateBulk) SaveX(ctx context.Context) []*ArticleVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArticleVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArticleVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArticleVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArticleVersionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ArticleVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ArticleVersionUpsertBulk {
	_c.conflict = opts
	return &ArticleVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArticleVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ArticleVersionCreateBulk) OnConflictColumns(columns ...string) *ArticleVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ArticleVersionUpsertBulk{
		create: _c,
	}
}

// ArticleVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of ArticleVersion nodes.
type ArticleVersionUpsertBulk struct {
	create *ArticleVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ArticleVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ArticleVersionUpsertBulk) UpdateNewValues() *ArticleVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(articleversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ArticleVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ArticleVersionUpsertBulk) Ignore() *ArticleVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArticleVersionUpsertBulk) DoNothing() *ArticleVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArticleVersionCreateBulk.OnConflict
// documentation for more info.
func (u *ArticleVersionUpsertBulk) Update(set func(*ArticleVersionUpsert)) *ArticleVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArticleVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArticleVersionUpsertBulk) SetUpdatedAt(v time.Time) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateUpdatedAt() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetArticleID sets the "article_id" field.
func (u *ArticleVersionUpsertBulk) SetArticleID(v int) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetArticleID(v)
	})
}

// UpdateArticleID sets the "article_id" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateArticleID() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateArticleID()
	})
}

// SetVersionNo sets the "version_no" field.
func (u *ArticleVersionUpsertBulk) SetVersionNo(v int) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetVersionNo(v)
	})
}

// AddVersionNo adds v to the "version_no" field.
func (u *ArticleVersionUpsertBulk) AddVersionNo(v int) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.AddVersionNo(v)
	})
}

// UpdateVersionNo sets the "version_no" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateVersionNo() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateVersionNo()
	})
}

// SetTitle sets the "title" field.
func (u *ArticleVersionUpsertBulk) SetTitle(v string) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateTitle() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *ArticleVersionUpsertBulk) SetContent(v string) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateContent() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *ArticleVersionUpsertBulk) ClearContent() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearContent()
	})
}

// SetCoverDescription sets the "cover_description" field.
func (u *ArticleVersionUpsertBulk) SetCoverDescription(v string) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetCoverDescription(v)
	})
}

// UpdateCoverDescription sets the "cover_description" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateCoverDescription() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateCoverDescription()
	})
}

// ClearCoverDescription clears the value of the "cover_description" field.
func (u *ArticleVersionUpsertBulk) ClearCoverDescription() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearCoverDescription()
	})
}

// SetSummary sets the "summary" field.
func (u *ArticleVersionUpsertBulk) SetSummary(v string) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateSummary() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *ArticleVersionUpsertBulk) ClearSummary() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearSummary()
	})
}

// SetStatus sets the "status" field.
func (u *ArticleVersionUpsertBulk) SetStatus(v string) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateStatus() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetEditorID sets the "editor_id" field.
func (u *ArticleVersionUpsertBulk) SetEditorID(v int) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetEditorID(v)
	})
}

// UpdateEditorID sets the "editor_id" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateEditorID() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateEditorID()
	})
}

// ClearEditorID clears the value of the "editor_id" field.
func (u *ArticleVersionUpsertBulk) ClearEditorID() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearEditorID()
	})
}

// SetEditReason sets the "edit_reason" field.
func (u *ArticleVersionUpsertBulk) SetEditReason(v string) *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.SetEditReason(v)
	})
}

// UpdateEditReason sets the "edit_reason" field to the value that was provided on create.
func (u *ArticleVersionUpsertBulk) UpdateEditReason() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.UpdateEditReason()
	})
}

// ClearEditReason clears the value of the "edit_reason" field.
func (u *ArticleVersionUpsertBulk) ClearEditReason() *ArticleVersionUpsertBulk {
	return u.Update(func(s *ArticleVersionUpsert) {
		s.ClearEditReason()
	})
}

// Exec executes the query.
func (u *ArticleVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ArticleVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArticleVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArticleVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
