// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"oa-nsdiy/backend/ent/article"
	"oa-nsdiy/backend/ent/articleversion"
	"oa-nsdiy/backend/ent/predicate"
	"oa-nsdiy/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticleVersionUpdate is the builder for updating ArticleVersion entities.
type ArticleVersionUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleVersionMutation
}

// Where appends a list predicates to the ArticleVersionUpdate builder.
func (_u *ArticleVersionUpdate) Where(ps ...predicate.ArticleVersion) *ArticleVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArticleVersionUpdate) SetUpdatedAt(v time.Time) *ArticleVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *ArticleVersionUpdate) SetArticleID(v int) *ArticleVersionUpdate {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *ArticleVersionUpdate) SetNillableArticleID(v *int) *ArticleVersionUpdate {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetVersionNo sets the "version_no" field.
func (_u *ArticleVersionUpdate) SetVersionNo(v int) *ArticleVersionUpdate {
	_u.mutation.ResetVersionNo()
	_u.mutation.SetVersionNo(v)
	return _u
}

// SetNillableVersionNo sets the "version_no" field if the given value is not nil.
func (_u *ArticleVersionUpdate) SetNillableVersionNo(v *int) *ArticleVersionUpdate {
	if v != nil {
		_u.SetVersionNo(*v)
	}
	return _u
}

// AddVersionNo adds value to the "version_no" field.
func (_u *ArticleVersionUpdate) AddVersionNo(v int) *ArticleVersionUpdate {
	_u.mutation.AddVersionNo(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ArticleVersionUpdate) SetTitle(v string) *ArticleVersionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleVersionUpdate) SetNillableTitle(v *string) *ArticleVersionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleVersionUpdate) SetContent(v string) *ArticleVersionUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleVersionUpdate) SetNillableContent(v *string) *ArticleVersionUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleVersionUpdate) ClearContent() *ArticleVersionUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetCoverDescription sets the "cover_description" field.
func (_u *ArticleVersionUpdate) SetCoverDescription(v string) *ArticleVersionUpdate {
	_u.mutation.SetCoverDescription(v)
	return _u
}

// SetNillableCoverDescription sets the "cover_description" field if the given value is not nil.
func (_u *ArticleVersionUpdate) SetNillableCoverDescription(v *string) *ArticleVersionUpdate {
	if v != nil {
		_u.SetCoverDescription(*v)
	}
	return _u
}

// ClearCoverDescription clears the value of the "cover_description" field.
func (_u *ArticleVersionUpdate) ClearCoverDescription() *ArticleVersionUpdate {
	_u.mutation.ClearCoverDescription()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ArticleVersionUpdate) SetSummary(v string) *ArticleVersionUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ArticleVersionUpdate) SetNillableSummary(v *string) *ArticleVersionUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *ArticleVersionUpdate) ClearSummary() *ArticleVersionUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ArticleVersionUpdate) SetStatus(v string) *ArticleVersionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ArticleVersionUpdate) SetNillableStatus(v *string) *ArticleVersionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEditorID sets the "editor_id" field.
func (_u *ArticleVersionUpdate) SetEditorID(v int) *ArticleVersionUpdate {
	_u.mutation.SetEditorID(v)
	return _u
}

// SetNillableEditorID sets the "editor_id" field if the given value is not nil.
func (_u *ArticleVersionUpdate) SetNillableEditorID(v *int) *ArticleVersionUpdate {
	if v != nil {
		_u.SetEditorID(*v)
	}
	return _u
}

// ClearEditorID clears the value of the "editor_id" field.
func (_u *ArticleVersionUpdate) ClearEditorID() *ArticleVersionUpdate {
	_u.mutation.ClearEditorID()
	return _u
}

// SetEditReason sets the "edit_reason" field.
func (_u *ArticleVersionUpdate) SetEditReason(v string) *ArticleVersionUpdate {
	_u.mutation.SetEditReason(v)
	return _u
}

// SetNillableEditReason sets the "edit_reason" field if the given value is not nil.
func (_u *ArticleVersionUpdate) SetNillableEditReason(v *string) *ArticleVersionUpdate {
	if v != nil {
		_u.SetEditReason(*v)
	}
	return _u
}

// ClearEditReason clears the value of the "edit_reason" field.
func (_u *ArticleVersionUpdate) ClearEditReason() *ArticleVersionUpdate {
	_u.mutation.ClearEditReason()
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *ArticleVersionUpdate) SetArticle(v *Article) *ArticleVersionUpdate {
	return _u.SetArticleID(v.ID)
}

// SetEditor sets the "editor" edge to the User entity.
func (_u *ArticleVersionUpdate) SetEditor(v *User) *ArticleVersionUpdate {
	return _u.SetEditorID(v.ID)
}

// Mutation returns the ArticleVersionMutation object of the builder.
func (_u *ArticleVersionUpdate) Mutation() *ArticleVersionMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *ArticleVersionUpdate) ClearArticle() *ArticleVersionUpdate {
	_u.mutation.ClearArticle()
	return _u
}

// ClearEditor clears the "editor" edge to the User entity.
func (_u *ArticleVersionUpdate) ClearEditor() *ArticleVersionUpdate {
	_u.mutation.ClearEditor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArticleVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArticleVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArticleVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := articleversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleVersionUpdate) check() error {
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := articleversion.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.article_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VersionNo(); ok {
		if err := articleversion.VersionNoValidator(v); err != nil {
			return &ValidationError{Name: "version_no", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.version_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := articleversion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverDescription(); ok {
		if err := articleversion.CoverDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "cover_description", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.cover_description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := articleversion.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := articleversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EditReason(); ok {
		if err := articleversion.EditReasonValidator(v); err != nil {
			return &ValidationError{Name: "edit_reason", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.edit_reason": %w`, err)}
		}
	}
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArticleVersion.article"`)
	}
	return nil
}

func (_u *ArticleVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(articleversion.Table, articleversion.Columns, sqlgraph.NewFieldSpec(articleversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(articleversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VersionNo(); ok {
		_spec.SetField(articleversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNo(); ok {
		_spec.AddField(articleversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(articleversion.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(articleversion.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(articleversion.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.CoverDescription(); ok {
		_spec.SetField(articleversion.FieldCoverDescription, field.TypeString, value)
	}
	if _u.mutation.CoverDescriptionCleared() {
		_spec.ClearField(articleversion.FieldCoverDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(articleversion.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(articleversion.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(articleversion.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditReason(); ok {
		_spec.SetField(articleversion.FieldEditReason, field.TypeString, value)
	}
	if _u.mutation.EditReasonCleared() {
		_spec.ClearField(articleversion.FieldEditReason, field.TypeString)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.ArticleTable,
			Columns: []string{articleversion.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.ArticleTable,
			Columns: []string{articleversion.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EditorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.EditorTable,
			Columns: []string{articleversion.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EditorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.EditorTable,
			Columns: []string{articleversion.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articleversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArticleVersionUpdateOne is the builder for updating a single ArticleVersion entity.
type ArticleVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleVersionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ArticleVersionUpdateOne) SetUpdatedAt(v time.Time) *ArticleVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *ArticleVersionUpdateOne) SetArticleID(v int) *ArticleVersionUpdateOne {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *ArticleVersionUpdateOne) SetNillableArticleID(v *int) *ArticleVersionUpdateOne {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetVersionNo sets the "version_no" field.
func (_u *ArticleVersionUpdateOne) SetVersionNo(v int) *ArticleVersionUpdateOne {
	_u.mutation.ResetVersionNo()
	_u.mutation.SetVersionNo(v)
	return _u
}

// SetNillableVersionNo sets the "version_no" field if the given value is not nil.
func (_u *ArticleVersionUpdateOne) SetNillableVersionNo(v *int) *ArticleVersionUpdateOne {
	if v != nil {
		_u.SetVersionNo(*v)
	}
	return _u
}

// AddVersionNo adds value to the "version_no" field.
func (_u *ArticleVersionUpdateOne) AddVersionNo(v int) *ArticleVersionUpdateOne {
	_u.mutation.AddVersionNo(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ArticleVersionUpdateOne) SetTitle(v string) *ArticleVersionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ArticleVersionUpdateOne) SetNillableTitle(v *string) *ArticleVersionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleVersionUpdateOne) SetContent(v string) *ArticleVersionUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleVersionUpdateOne) SetNillableContent(v *string) *ArticleVersionUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleVersionUpdateOne) ClearContent() *ArticleVersionUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetCoverDescription sets the "cover_description" field.
func (_u *ArticleVersionUpdateOne) SetCoverDescription(v string) *ArticleVersionUpdateOne {
	_u.mutation.SetCoverDescription(v)
	return _u
}

// SetNillableCoverDescription sets the "cover_description" field if the given value is not nil.
func (_u *ArticleVersionUpdateOne) SetNillableCoverDescription(v *string) *ArticleVersionUpdateOne {
	if v != nil {
		_u.SetCoverDescription(*v)
	}
	return _u
}

// ClearCoverDescription clears the value of the "cover_description" field.
func (_u *ArticleVersionUpdateOne) ClearCoverDescription() *ArticleVersionUpdateOne {
	_u.mutation.ClearCoverDescription()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ArticleVersionUpdateOne) SetSummary(v string) *ArticleVersionUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ArticleVersionUpdateOne) SetNillableSummary(v *string) *ArticleVersionUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *ArticleVersionUpdateOne) ClearSummary() *ArticleVersionUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ArticleVersionUpdateOne) SetStatus(v string) *ArticleVersionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ArticleVersionUpdateOne) SetNillableStatus(v *string) *ArticleVersionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEditorID sets the "editor_id" field.
func (_u *ArticleVersionUpdateOne) SetEditorID(v int) *ArticleVersionUpdateOne {
	_u.mutation.SetEditorID(v)
	return _u
}

// SetNillableEditorID sets the "editor_id" field if the given value is not nil.
func (_u *ArticleVersionUpdateOne) SetNillableEditorID(v *int) *ArticleVersionUpdateOne {
	if v != nil {
		_u.SetEditorID(*v)
	}
	return _u
}

// ClearEditorID clears the value of the "editor_id" field.
func (_u *ArticleVersionUpdateOne) ClearEditorID() *ArticleVersionUpdateOne {
	_u.mutation.ClearEditorID()
	return _u
}

// SetEditReason sets the "edit_reason" field.
func (_u *ArticleVersionUpdateOne) SetEditReason(v string) *ArticleVersionUpdateOne {
	_u.mutation.SetEditReason(v)
	return _u
}

// SetNillableEditReason sets the "edit_reason" field if the given value is not nil.
func (_u *ArticleVersionUpdateOne) SetNillableEditReason(v *string) *ArticleVersionUpdateOne {
	if v != nil {
		_u.SetEditReason(*v)
	}
	return _u
}

// ClearEditReason clears the value of the "edit_reason" field.
func (_u *ArticleVersionUpdateOne) ClearEditReason() *ArticleVersionUpdateOne {
	_u.mutation.ClearEditReason()
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *ArticleVersionUpdateOne) SetArticle(v *Article) *ArticleVersionUpdateOne {
	return _u.SetArticleID(v.ID)
}

// SetEditor sets the "editor" edge to the User entity.
func (_u *ArticleVersionUpdateOne) SetEditor(v *User) *ArticleVersionUpdateOne {
	return _u.SetEditorID(v.ID)
}

// Mutation returns the ArticleVersionMutation object of the builder.
func (_u *ArticleVersionUpdateOne) Mutation() *ArticleVersionMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *ArticleVersionUpdateOne) ClearArticle() *ArticleVersionUpdateOne {
	_u.mutation.ClearArticle()
	return _u
}

// ClearEditor clears the "editor" edge to the User entity.
func (_u *ArticleVersionUpdateOne) ClearEditor() *ArticleVersionUpdateOne {
	_u.mutation.ClearEditor()
	return _u
}

// Where appends a list predicates to the ArticleVersionUpdate builder.
func (_u *ArticleVersionUpdateOne) Where(ps ...predicate.ArticleVersion) *ArticleVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArticleVersionUpdateOne) Select(field string, fields ...string) *ArticleVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ArticleVersion entity.
func (_u *ArticleVersionUpdateOne) Save(ctx context.Context) (*ArticleVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleVersionUpdateOne) SaveX(ctx context.Context) *ArticleVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArticleVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArticleVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := articleversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleVersionUpdateOne) check() error {
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := articleversion.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.article_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VersionNo(); ok {
		if err := articleversion.VersionNoValidator(v); err != nil {
			return &ValidationError{Name: "version_no", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.version_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := articleversion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverDescription(); ok {
		if err := articleversion.CoverDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "cover_description", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.cover_description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := articleversion.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := articleversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EditReason(); ok {
		if err := articleversion.EditReasonValidator(v); err != nil {
			return &ValidationError{Name: "edit_reason", err: fmt.Errorf(`ent: validator failed for field "ArticleVersion.edit_reason": %w`, err)}
		}
	}
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ArticleVersion.article"`)
	}
	return nil
}

func (_u *ArticleVersionUpdateOne) sqlSave(ctx context.Context) (_node *ArticleVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(articleversion.Table, articleversion.Columns, sqlgraph.NewFieldSpec(articleversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ArticleVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, articleversion.FieldID)
		for _, f := range fields {
			if !articleversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != articleversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(articleversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VersionNo(); ok {
		_spec.SetField(articleversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNo(); ok {
		_spec.AddField(articleversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(articleversion.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(articleversion.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(articleversion.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.CoverDescription(); ok {
		_spec.SetField(articleversion.FieldCoverDescription, field.TypeString, value)
	}
	if _u.mutation.CoverDescriptionCleared() {
		_spec.ClearField(articleversion.FieldCoverDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(articleversion.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(articleversion.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(articleversion.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditReason(); ok {
		_spec.SetField(articleversion.FieldEditReason, field.TypeString, value)
	}
	if _u.mutation.EditReasonCleared() {
		_spec.ClearField(articleversion.FieldEditReason, field.TypeString)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.ArticleTable,
			Columns: []string{articleversion.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.ArticleTable,
			Columns: []string{articleversion.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EditorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.EditorTable,
			Columns: []string{articleversion.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EditorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   articleversion.EditorTable,
			Columns: []string{articleversion.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ArticleVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articleversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
