// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"oa-nsdiy/backend/ent/mediacontentversion"
	"oa-nsdiy/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaContentVersionDelete is the builder for deleting a MediaContentVersion entity.
type MediaContentVersionDelete struct {
	config
	hooks    []Hook
	mutation *MediaContentVersionMutation
}

// Where appends a list predicates to the MediaContentVersionDelete builder.
func (_d *MediaContentVersionDelete) Where(ps ...predicate.MediaContentVersion) *MediaContentVersionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MediaContentVersionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaContentVersionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MediaContentVersionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mediacontentversion.Table, sqlgraph.NewFieldSpec(mediacontentversion.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MediaContentVersionDeleteOne is the builder for deleting a single MediaContentVersion entity.
type MediaContentVersionDeleteOne struct {
	_d *MediaContentVersionDelete
}

// Where appends a list predicates to the MediaContentVersionDelete builder.
func (_d *MediaContentVersionDeleteOne) Where(ps ...predicate.MediaContentVersion) *MediaContentVersionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MediaContentVersionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediacontentversion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaContentVersionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
