// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"oa-nsdiy/backend/ent/mediacontent"
	"oa-nsdiy/backend/ent/mediacontentversion"
	"oa-nsdiy/backend/ent/predicate"
	"oa-nsdiy/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaContentVersionUpdate is the builder for updating MediaContentVersion entities.
type MediaContentVersionUpdate struct {
	config
	hooks    []Hook
	mutation *MediaContentVersionMutation
}

// Where appends a list predicates to the MediaContentVersionUpdate builder.
func (_u *MediaContentVersionUpdate) Where(ps ...predicate.MediaContentVersion) *MediaContentVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaContentVersionUpdate) SetUpdatedAt(v time.Time) *MediaContentVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetContentID sets the "content_id" field.
func (_u *MediaContentVersionUpdate) SetContentID(v int) *MediaContentVersionUpdate {
	_u.mutation.SetContentID(v)
	return _u
}

// SetNillableContentID sets the "content_id" field if the given value is not nil.
func (_u *MediaContentVersionUpdate) SetNillableContentID(v *int) *MediaContentVersionUpdate {
	if v != nil {
		_u.SetContentID(*v)
	}
	return _u
}

// SetVersionNo sets the "version_no" field.
func (_u *MediaContentVersionUpdate) SetVersionNo(v int) *MediaContentVersionUpdate {
	_u.mutation.ResetVersionNo()
	_u.mutation.SetVersionNo(v)
	return _u
}

// SetNillableVersionNo sets the "version_no" field if the given value is not nil.
func (_u *MediaContentVersionUpdate) SetNillableVersionNo(v *int) *MediaContentVersionUpdate {
	if v != nil {
		_u.SetVersionNo(*v)
	}
	return _u
}

// AddVersionNo adds value to the "version_no" field.
func (_u *MediaContentVersionUpdate) AddVersionNo(v int) *MediaContentVersionUpdate {
	_u.mutation.AddVersionNo(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MediaContentVersionUpdate) SetTitle(v string) *MediaContentVersionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MediaContentVersionUpdate) SetNillableTitle(v *string) *MediaContentVersionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MediaContentVersionUpdate) SetContent(v string) *MediaContentVersionUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MediaContentVersionUpdate) SetNillableContent(v *string) *MediaContentVersionUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MediaContentVersionUpdate) ClearContent() *MediaContentVersionUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *MediaContentVersionUpdate) SetCoverImage(v string) *MediaContentVersionUpdate {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *MediaContentVersionUpdate) SetNillableCoverImage(v *string) *MediaContentVersionUpdate {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *MediaContentVersionUpdate) ClearCoverImage() *MediaContentVersionUpdate {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaContentVersionUpdate) SetStatus(v string) *MediaContentVersionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaContentVersionUpdate) SetNillableStatus(v *string) *MediaContentVersionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEditorID sets the "editor_id" field.
func (_u *MediaContentVersionUpdate) SetEditorID(v int) *MediaContentVersionUpdate {
	_u.mutation.SetEditorID(v)
	return _u
}

// SetNillableEditorID sets the "editor_id" field if the given value is not nil.
func (_u *MediaContentVersionUpdate) SetNillableEditorID(v *int) *MediaContentVersionUpdate {
	if v != nil {
		_u.SetEditorID(*v)
	}
	return _u
}

// ClearEditorID clears the value of the "editor_id" field.
func (_u *MediaContentVersionUpdate) ClearEditorID() *MediaContentVersionUpdate {
	_u.mutation.ClearEditorID()
	return _u
}

// SetEditReason sets the "edit_reason" field.
func (_u *MediaContentVersionUpdate) SetEditReason(v string) *MediaContentVersionUpdate {
	_u.mutation.SetEditReason(v)
	return _u
}

// SetNillableEditReason sets the "edit_reason" field if the given value is not nil.
func (_u *MediaContentVersionUpdate) SetNillableEditReason(v *string) *MediaContentVersionUpdate {
	if v != nil {
		_u.SetEditReason(*v)
	}
	return _u
}

// ClearEditReason clears the value of the "edit_reason" field.
func (_u *MediaContentVersionUpdate) ClearEditReason() *MediaContentVersionUpdate {
	_u.mutation.ClearEditReason()
	return _u
}

// SetMediaContentID sets the "media_content" edge to the MediaContent entity by ID.
func (_u *MediaContentVersionUpdate) SetMediaContentID(id int) *MediaContentVersionUpdate {
	_u.mutation.SetMediaContentID(id)
	return _u
}

// SetMediaContent sets the "media_content" edge to the MediaContent entity.
func (_u *MediaContentVersionUpdate) SetMediaContent(v *MediaContent) *MediaContentVersionUpdate {
	return _u.SetMediaContentID(v.ID)
}

// SetEditor sets the "editor" edge to the User entity.
func (_u *MediaContentVersionUpdate) SetEditor(v *User) *MediaContentVersionUpdate {
	return _u.SetEditorID(v.ID)
}

// Mutation returns the MediaContentVersionMutation object of the builder.
func (_u *MediaContentVersionUpdate) Mutation() *MediaContentVersionMutation {
	return _u.mutation
}

// ClearMediaContent clears the "media_content" edge to the MediaContent entity.
func (_u *MediaContentVersionUpdate) ClearMediaContent() *MediaContentVersionUpdate {
	_u.mutation.ClearMediaContent()
	return _u
}

// ClearEditor clears the "editor" edge to the User entity.
func (_u *MediaContentVersionUpdate) ClearEditor() *MediaContentVersionUpdate {
	_u.mutation.ClearEditor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaContentVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaContentVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaContentVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaContentVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaContentVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediacontentversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaContentVersionUpdate) check() error {
	if v, ok := _u.mutation.ContentID(); ok {
		if err := mediacontentversion.ContentIDValidator(v); err != nil {
			return &ValidationError{Name: "content_id", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.content_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VersionNo(); ok {
		if err := mediacontentversion.VersionNoValidator(v); err != nil {
			return &ValidationError{Name: "version_no", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.version_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := mediacontentversion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := mediacontentversion.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediacontentversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EditReason(); ok {
		if err := mediacontentversion.EditReasonValidator(v); err != nil {
			return &ValidationError{Name: "edit_reason", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.edit_reason": %w`, err)}
		}
	}
	if _u.mutation.MediaContentCleared() && len(_u.mutation.MediaContentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaContentVersion.media_content"`)
	}
	return nil
}

func (_u *MediaContentVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediacontentversion.Table, mediacontentversion.Columns, sqlgraph.NewFieldSpec(mediacontentversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediacontentversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VersionNo(); ok {
		_spec.SetField(mediacontentversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNo(); ok {
		_spec.AddField(mediacontentversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(mediacontentversion.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(mediacontentversion.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(mediacontentversion.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(mediacontentversion.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(mediacontentversion.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediacontentversion.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditReason(); ok {
		_spec.SetField(mediacontentversion.FieldEditReason, field.TypeString, value)
	}
	if _u.mutation.EditReasonCleared() {
		_spec.ClearField(mediacontentversion.FieldEditReason, field.TypeString)
	}
	if _u.mutation.MediaContentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediacontentversion.MediaContentTable,
			Columns: []string{mediacontentversion.MediaContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediacontent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaContentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediacontentversion.MediaContentTable,
			Columns: []string{mediacontentversion.MediaContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediacontent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EditorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediacontentversion.EditorTable,
			Columns: []string{mediacontentversion.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EditorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediacontentversion.EditorTable,
			Columns: []string{mediacontentversion.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediacontentversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaContentVersionUpdateOne is the builder for updating a single MediaContentVersion entity.
type MediaContentVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaContentVersionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaContentVersionUpdateOne) SetUpdatedAt(v time.Time) *MediaContentVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetContentID sets the "content_id" field.
func (_u *MediaContentVersionUpdateOne) SetContentID(v int) *MediaContentVersionUpdateOne {
	_u.mutation.SetContentID(v)
	return _u
}

// SetNillableContentID sets the "content_id" field if the given value is not nil.
func (_u *MediaContentVersionUpdateOne) SetNillableContentID(v *int) *MediaContentVersionUpdateOne {
	if v != nil {
		_u.SetContentID(*v)
	}
	return _u
}

// SetVersionNo sets the "version_no" field.
func (_u *MediaContentVersionUpdateOne) SetVersionNo(v int) *MediaContentVersionUpdateOne {
	_u.mutation.ResetVersionNo()
	_u.mutation.SetVersionNo(v)
	return _u
}

// SetNillableVersionNo sets the "version_no" field if the given value is not nil.
func (_u *MediaContentVersionUpdateOne) SetNillableVersionNo(v *int) *MediaContentVersionUpdateOne {
	if v != nil {
		_u.SetVersionNo(*v)
	}
	return _u
}

// AddVersionNo adds value to the "version_no" field.
func (_u *MediaContentVersionUpdateOne) AddVersionNo(v int) *MediaContentVersionUpdateOne {
	_u.mutation.AddVersionNo(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MediaContentVersionUpdateOne) SetTitle(v string) *MediaContentVersionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MediaContentVersionUpdateOne) SetNillableTitle(v *string) *MediaContentVersionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MediaContentVersionUpdateOne) SetContent(v string) *MediaContentVersionUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MediaContentVersionUpdateOne) SetNillableContent(v *string) *MediaContentVersionUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MediaContentVersionUpdateOne) ClearContent() *MediaContentVersionUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *MediaContentVersionUpdateOne) SetCoverImage(v string) *MediaContentVersionUpdateOne {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *MediaContentVersionUpdateOne) SetNillableCoverImage(v *string) *MediaContentVersionUpdateOne {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *MediaContentVersionUpdateOne) ClearCoverImage() *MediaContentVersionUpdateOne {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaContentVersionUpdateOne) SetStatus(v string) *MediaContentVersionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaContentVersionUpdateOne) SetNillableStatus(v *string) *MediaContentVersionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEditorID sets the "editor_id" field.
func (_u *MediaContentVersionUpdateOne) SetEditorID(v int) *MediaContentVersionUpdateOne {
	_u.mutation.SetEditorID(v)
	return _u
}

// SetNillableEditorID sets the "editor_id" field if the given value is not nil.
func (_u *MediaContentVersionUpdateOne) SetNillableEditorID(v *int) *MediaContentVersionUpdateOne {
	if v != nil {
		_u.SetEditorID(*v)
	}
	return _u
}

// ClearEditorID clears the value of the "editor_id" field.
func (_u *MediaContentVersionUpdateOne) ClearEditorID() *MediaContentVersionUpdateOne {
	_u.mutation.ClearEditorID()
	return _u
}

// SetEditReason sets the "edit_reason" field.
func (_u *MediaContentVersionUpdateOne) SetEditReason(v string) *MediaContentVersionUpdateOne {
	_u.mutation.SetEditReason(v)
	return _u
}

// SetNillableEditReason sets the "edit_reason" field if the given value is not nil.
func (_u *MediaContentVersionUpdateOne) SetNillableEditReason(v *string) *MediaContentVersionUpdateOne {
	if v != nil {
		_u.SetEditReason(*v)
	}
	return _u
}

// ClearEditReason clears the value of the "edit_reason" field.
func (_u *MediaContentVersionUpdateOne) ClearEditReason() *MediaContentVersionUpdateOne {
	_u.mutation.ClearEditReason()
	return _u
}

// SetMediaContentID sets the "media_content" edge to the MediaContent entity by ID.
func (_u *MediaContentVersionUpdateOne) SetMediaContentID(id int) *MediaContentVersionUpdateOne {
	_u.mutation.SetMediaContentID(id)
	return _u
}

// SetMediaContent sets the "media_content" edge to the MediaContent entity.
func (_u *MediaContentVersionUpdateOne) SetMediaContent(v *MediaContent) *MediaContentVersionUpdateOne {
	return _u.SetMediaContentID(v.ID)
}

// SetEditor sets the "editor" edge to the User entity.
func (_u *MediaContentVersionUpdateOne) SetEditor(v *User) *MediaContentVersionUpdateOne {
	return _u.SetEditorID(v.ID)
}

// Mutation returns the MediaContentVersionMutation object of the builder.
func (_u *MediaContentVersionUpdateOne) Mutation() *MediaContentVersionMutation {
	return _u.mutation
}

// ClearMediaContent clears the "media_content" edge to the MediaContent entity.
func (_u *MediaContentVersionUpdateOne) ClearMediaContent() *MediaContentVersionUpdateOne {
	_u.mutation.ClearMediaContent()
	return _u
}

// ClearEditor clears the "editor" edge to the User entity.
func (_u *MediaContentVersionUpdateOne) ClearEditor() *MediaContentVersionUpdateOne {
	_u.mutation.ClearEditor()
	return _u
}

// Where appends a list predicates to the MediaContentVersionUpdate builder.
func (_u *MediaContentVersionUpdateOne) Where(ps ...predicate.MediaContentVersion) *MediaContentVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaContentVersionUpdateOne) Select(field string, fields ...string) *MediaContentVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaContentVersion entity.
func (_u *MediaContentVersionUpdateOne) Save(ctx context.Context) (*MediaContentVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaContentVersionUpdateOne) SaveX(ctx context.Context) *MediaContentVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaContentVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaContentVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaContentVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediacontentversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaContentVersionUpdateOne) check() error {
	if v, ok := _u.mutation.ContentID(); ok {
		if err := mediacontentversion.ContentIDValidator(v); err != nil {
			return &ValidationError{Name: "content_id", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.content_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VersionNo(); ok {
		if err := mediacontentversion.VersionNoValidator(v); err != nil {
			return &ValidationError{Name: "version_no", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.version_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := mediacontentversion.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := mediacontentversion.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediacontentversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EditReason(); ok {
		if err := mediacontentversion.EditReasonValidator(v); err != nil {
			return &ValidationError{Name: "edit_reason", err: fmt.Errorf(`ent: validator failed for field "MediaContentVersion.edit_reason": %w`, err)}
		}
	}
	if _u.mutation.MediaContentCleared() && len(_u.mutation.MediaContentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaContentVersion.media_content"`)
	}
	return nil
}

func (_u *MediaContentVersionUpdateOne) sqlSave(ctx context.Context) (_node *MediaContentVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediacontentversion.Table, mediacontentversion.Columns, sqlgraph.NewFieldSpec(mediacontentversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaContentVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediacontentversion.FieldID)
		for _, f := range fields {
			if !mediacontentversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediacontentversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediacontentversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.VersionNo(); ok {
		_spec.SetField(mediacontentversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNo(); ok {
		_spec.AddField(mediacontentversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(mediacontentversion.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(mediacontentversion.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(mediacontentversion.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(mediacontentversion.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(mediacontentversion.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediacontentversion.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.EditReason(); ok {
		_spec.SetField(mediacontentversion.FieldEditReason, field.TypeString, value)
	}
	if _u.mutation.EditReasonCleared() {
		_spec.ClearField(mediacontentversion.FieldEditReason, field.TypeString)
	}
	if _u.mutation.MediaContentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediacontentversion.MediaContentTable,
			Columns: []string{mediacontentversion.MediaContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediacontent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaContentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediacontentversion.MediaContentTable,
			Columns: []string{mediacontentversion.MediaContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediacontent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EditorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediacontentversion.EditorTable,
			Columns: []string{mediacontentversion.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EditorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediacontentversion.EditorTable,
			Columns: []string{mediacontentversion.EditorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MediaContentVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediacontentversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
