// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"oa-nsdiy/backend/ent/mediacontent"
	"oa-nsdiy/backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaContentDelete is the builder for deleting a MediaContent entity.
type MediaContentDelete struct {
	config
	hooks    []Hook
	mutation *MediaContentMutation
}

// Where appends a list predicates to the MediaContentDelete builder.
func (_d *MediaContentDelete) Where(ps ...predicate.MediaContent) *MediaContentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MediaContentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaContentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MediaContentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mediacontent.Table, sqlgraph.NewFieldSpec(mediacontent.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MediaContentDeleteOne is the builder for deleting a single MediaContent entity.
type MediaContentDeleteOne struct {
	_d *MediaContentDelete
}

// Where appends a list predicates to the MediaContentDelete builder.
func (_d *MediaContentDeleteOne) Where(ps ...predicate.MediaContent) *MediaContentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MediaContentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mediacontent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MediaContentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
