// Code generated by ent, DO NOT EDIT.

package ent

import (
	"oa-nsdiy/backend/ent/apitoken"
	"oa-nsdiy/backend/ent/article"
	"oa-nsdiy/backend/ent/articleversion"
	"oa-nsdiy/backend/ent/mediaaccount"
	"oa-nsdiy/backend/ent/mediaaccountfanssnapshot"
	"oa-nsdiy/backend/ent/mediacontent"
	"oa-nsdiy/backend/ent/mediacontentversion"
	"oa-nsdiy/backend/ent/news"
	"oa-nsdiy/backend/ent/newsgroup"
	"oa-nsdiy/backend/ent/operationlog"
	"oa-nsdiy/backend/ent/permission"
	"oa-nsdiy/backend/ent/project"
	"oa-nsdiy/backend/ent/projectmember"
	"oa-nsdiy/backend/ent/role"
	"oa-nsdiy/backend/ent/roleperm"
	"oa-nsdiy/backend/ent/schema"
	"oa-nsdiy/backend/ent/task"
	"oa-nsdiy/backend/ent/uploadfile"
	"oa-nsdiy/backend/ent/user"
	"oa-nsdiy/backend/ent/verificationcode"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apitokenMixin := schema.ApiToken{}.Mixin()
	apitokenMixinFields0 := apitokenMixin[0].Fields()
	_ = apitokenMixinFields0
	apitokenFields := schema.ApiToken{}.Fields()
	_ = apitokenFields
	// apitokenDescCreatedAt is the schema descriptor for created_at field.
	apitokenDescCreatedAt := apitokenMixinFields0[0].Descriptor()
	// apitoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	apitoken.DefaultCreatedAt = apitokenDescCreatedAt.Default.(func() time.Time)
	// apitokenDescUpdatedAt is the schema descriptor for updated_at field.
	apitokenDescUpdatedAt := apitokenMixinFields0[1].Descriptor()
	// apitoken.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apitoken.DefaultUpdatedAt = apitokenDescUpdatedAt.Default.(func() time.Time)
	// apitoken.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apitoken.UpdateDefaultUpdatedAt = apitokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apitokenDescUserID is the schema descriptor for user_id field.
	apitokenDescUserID := apitokenFields[0].Descriptor()
	// apitoken.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	apitoken.UserIDValidator = apitokenDescUserID.Validators[0].(func(int) error)
	// apitokenDescName is the schema descriptor for name field.
	apitokenDescName := apitokenFields[1].Descriptor()
	// apitoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apitoken.NameValidator = func() func(string) error {
		validators := apitokenDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apitokenDescTokenHash is the schema descriptor for token_hash field.
	apitokenDescTokenHash := apitokenFields[2].Descriptor()
	// apitoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	apitoken.TokenHashValidator = apitokenDescTokenHash.Validators[0].(func(string) error)
	// apitokenDescTokenPrefix is the schema descriptor for token_prefix field.
	apitokenDescTokenPrefix := apitokenFields[3].Descriptor()
	// apitoken.TokenPrefixValidator is a validator for the "token_prefix" field. It is called by the builders before save.
	apitoken.TokenPrefixValidator = func() func(string) error {
		validators := apitokenDescTokenPrefix.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token_prefix string) error {
			for _, fn := range fns {
				if err := fn(token_prefix); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// apitokenDescStatus is the schema descriptor for status field.
	apitokenDescStatus := apitokenFields[4].Descriptor()
	// apitoken.DefaultStatus holds the default value on creation for the status field.
	apitoken.DefaultStatus = apitokenDescStatus.Default.(string)
	// apitoken.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	apitoken.StatusValidator = apitokenDescStatus.Validators[0].(func(string) error)
	// apitokenDescUsageCount is the schema descriptor for usage_count field.
	apitokenDescUsageCount := apitokenFields[7].Descriptor()
	// apitoken.DefaultUsageCount holds the default value on creation for the usage_count field.
	apitoken.DefaultUsageCount = apitokenDescUsageCount.Default.(int)
	articleMixin := schema.Article{}.Mixin()
	articleMixinFields0 := articleMixin[0].Fields()
	_ = articleMixinFields0
	articleFields := schema.Article{}.Fields()
	_ = articleFields
	// articleDescCreatedAt is the schema descriptor for created_at field.
	articleDescCreatedAt := articleMixinFields0[0].Descriptor()
	// article.DefaultCreatedAt holds the default value on creation for the created_at field.
	article.DefaultCreatedAt = articleDescCreatedAt.Default.(func() time.Time)
	// articleDescUpdatedAt is the schema descriptor for updated_at field.
	articleDescUpdatedAt := articleMixinFields0[1].Descriptor()
	// article.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	article.DefaultUpdatedAt = articleDescUpdatedAt.Default.(func() time.Time)
	// article.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	article.UpdateDefaultUpdatedAt = articleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// articleDescArticleNo is the schema descriptor for article_no field.
	articleDescArticleNo := articleFields[0].Descriptor()
	// article.ArticleNoValidator is a validator for the "article_no" field. It is called by the builders before save.
	article.ArticleNoValidator = func() func(string) error {
		validators := articleDescArticleNo.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(article_no string) error {
			for _, fn := range fns {
				if err := fn(article_no); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// articleDescTitle is the schema descriptor for title field.
	articleDescTitle := articleFields[1].Descriptor()
	// article.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	article.TitleValidator = func() func(string) error {
		validators := articleDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// articleDescSummary is the schema descriptor for summary field.
	articleDescSummary := articleFields[3].Descriptor()
	// article.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	article.SummaryValidator = articleDescSummary.Validators[0].(func(string) error)
	// articleDescStatus is the schema descriptor for status field.
	articleDescStatus := articleFields[4].Descriptor()
	// article.DefaultStatus holds the default value on creation for the status field.
	article.DefaultStatus = articleDescStatus.Default.(string)
	// article.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	article.StatusValidator = articleDescStatus.Validators[0].(func(string) error)
	// articleDescAuthorID is the schema descriptor for author_id field.
	articleDescAuthorID := articleFields[5].Descriptor()
	// article.AuthorIDValidator is a validator for the "author_id" field. It is called by the builders before save.
	article.AuthorIDValidator = articleDescAuthorID.Validators[0].(func(int) error)
	// articleDescCoverDescription is the schema descriptor for cover_description field.
	articleDescCoverDescription := articleFields[6].Descriptor()
	// article.CoverDescriptionValidator is a validator for the "cover_description" field. It is called by the builders before save.
	article.CoverDescriptionValidator = articleDescCoverDescription.Validators[0].(func(string) error)
	// articleDescCoverURL is the schema descriptor for cover_url field.
	articleDescCoverURL := articleFields[7].Descriptor()
	// article.CoverURLValidator is a validator for the "cover_url" field. It is called by the builders before save.
	article.CoverURLValidator = articleDescCoverURL.Validators[0].(func(string) error)
	articleversionMixin := schema.ArticleVersion{}.Mixin()
	articleversionMixinFields0 := articleversionMixin[0].Fields()
	_ = articleversionMixinFields0
	articleversionFields := schema.ArticleVersion{}.Fields()
	_ = articleversionFields
	// articleversionDescCreatedAt is the schema descriptor for created_at field.
	articleversionDescCreatedAt := articleversionMixinFields0[0].Descriptor()
	// articleversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	articleversion.DefaultCreatedAt = articleversionDescCreatedAt.Default.(func() time.Time)
	// articleversionDescUpdatedAt is the schema descriptor for updated_at field.
	articleversionDescUpdatedAt := articleversionMixinFields0[1].Descriptor()
	// articleversion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	articleversion.DefaultUpdatedAt = articleversionDescUpdatedAt.Default.(func() time.Time)
	// articleversion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	articleversion.UpdateDefaultUpdatedAt = articleversionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// articleversionDescArticleID is the schema descriptor for article_id field.
	articleversionDescArticleID := articleversionFields[0].Descriptor()
	// articleversion.ArticleIDValidator is a validator for the "article_id" field. It is called by the builders before save.
	articleversion.ArticleIDValidator = articleversionDescArticleID.Validators[0].(func(int) error)
	// articleversionDescVersionNo is the schema descriptor for version_no field.
	articleversionDescVersionNo := articleversionFields[1].Descriptor()
	// articleversion.VersionNoValidator is a validator for the "version_no" field. It is called by the builders before save.
	articleversion.VersionNoValidator = articleversionDescVersionNo.Validators[0].(func(int) error)
	// articleversionDescTitle is the schema descriptor for title field.
	articleversionDescTitle := articleversionFields[2].Descriptor()
	// articleversion.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	articleversion.TitleValidator = func() func(string) error {
		validators := articleversionDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// articleversionDescCoverDescription is the schema descriptor for cover_description field.
	articleversionDescCoverDescription := articleversionFields[4].Descriptor()
	// articleversion.CoverDescriptionValidator is a validator for the "cover_description" field. It is called by the builders before save.
	articleversion.CoverDescriptionValidator = articleversionDescCoverDescription.Validators[0].(func(string) error)
	// articleversionDescSummary is the schema descriptor for summary field.
	articleversionDescSummary := articleversionFields[5].Descriptor()
	// articleversion.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	articleversion.SummaryValidator = articleversionDescSummary.Validators[0].(func(string) error)
	// articleversionDescStatus is the schema descriptor for status field.
	articleversionDescStatus := articleversionFields[6].Descriptor()
	// articleversion.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	articleversion.StatusValidator = func() func(string) error {
		validators := articleversionDescStatus.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(status string) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// articleversionDescEditReason is the schema descriptor for edit_reason field.
	articleversionDescEditReason := articleversionFields[8].Descriptor()
	// articleversion.EditReasonValidator is a validator for the "edit_reason" field. It is called by the builders before save.
	articleversion.EditReasonValidator = articleversionDescEditReason.Validators[0].(func(string) error)
	mediaaccountMixin := schema.MediaAccount{}.Mixin()
	mediaaccountMixinFields0 := mediaaccountMixin[0].Fields()
	_ = mediaaccountMixinFields0
	mediaaccountFields := schema.MediaAccount{}.Fields()
	_ = mediaaccountFields
	// mediaaccountDescCreatedAt is the schema descriptor for created_at field.
	mediaaccountDescCreatedAt := mediaaccountMixinFields0[0].Descriptor()
	// mediaaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	mediaaccount.DefaultCreatedAt = mediaaccountDescCreatedAt.Default.(func() time.Time)
	// mediaaccountDescUpdatedAt is the schema descriptor for updated_at field.
	mediaaccountDescUpdatedAt := mediaaccountMixinFields0[1].Descriptor()
	// mediaaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mediaaccount.DefaultUpdatedAt = mediaaccountDescUpdatedAt.Default.(func() time.Time)
	// mediaaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mediaaccount.UpdateDefaultUpdatedAt = mediaaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mediaaccountDescName is the schema descriptor for name field.
	mediaaccountDescName := mediaaccountFields[0].Descriptor()
	// mediaaccount.NameValidator is a validator for the "name" field. It is called by the builders before save.
	mediaaccount.NameValidator = func() func(string) error {
		validators := mediaaccountDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mediaaccountDescPlatform is the schema descriptor for platform field.
	mediaaccountDescPlatform := mediaaccountFields[1].Descriptor()
	// mediaaccount.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	mediaaccount.PlatformValidator = func() func(string) error {
		validators := mediaaccountDescPlatform.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(platform string) error {
			for _, fn := range fns {
				if err := fn(platform); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mediaaccountDescAccountID is the schema descriptor for account_id field.
	mediaaccountDescAccountID := mediaaccountFields[2].Descriptor()
	// mediaaccount.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	mediaaccount.AccountIDValidator = func() func(string) error {
		validators := mediaaccountDescAccountID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(account_id string) error {
			for _, fn := range fns {
				if err := fn(account_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mediaaccountDescAvatar is the schema descriptor for avatar field.
	mediaaccountDescAvatar := mediaaccountFields[3].Descriptor()
	// mediaaccount.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	mediaaccount.AvatarValidator = mediaaccountDescAvatar.Validators[0].(func(string) error)
	// mediaaccountDescStatus is the schema descriptor for status field.
	mediaaccountDescStatus := mediaaccountFields[4].Descriptor()
	// mediaaccount.DefaultStatus holds the default value on creation for the status field.
	mediaaccount.DefaultStatus = mediaaccountDescStatus.Default.(string)
	// mediaaccount.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	mediaaccount.StatusValidator = mediaaccountDescStatus.Validators[0].(func(string) error)
	// mediaaccountDescAccessToken is the schema descriptor for access_token field.
	mediaaccountDescAccessToken := mediaaccountFields[5].Descriptor()
	// mediaaccount.AccessTokenValidator is a validator for the "access_token" field. It is called by the builders before save.
	mediaaccount.AccessTokenValidator = mediaaccountDescAccessToken.Validators[0].(func(string) error)
	// mediaaccountDescRefreshToken is the schema descriptor for refresh_token field.
	mediaaccountDescRefreshToken := mediaaccountFields[6].Descriptor()
	// mediaaccount.RefreshTokenValidator is a validator for the "refresh_token" field. It is called by the builders before save.
	mediaaccount.RefreshTokenValidator = mediaaccountDescRefreshToken.Validators[0].(func(string) error)
	mediaaccountfanssnapshotMixin := schema.MediaAccountFansSnapshot{}.Mixin()
	mediaaccountfanssnapshotMixinFields0 := mediaaccountfanssnapshotMixin[0].Fields()
	_ = mediaaccountfanssnapshotMixinFields0
	mediaaccountfanssnapshotFields := schema.MediaAccountFansSnapshot{}.Fields()
	_ = mediaaccountfanssnapshotFields
	// mediaaccountfanssnapshotDescCreatedAt is the schema descriptor for created_at field.
	mediaaccountfanssnapshotDescCreatedAt := mediaaccountfanssnapshotMixinFields0[0].Descriptor()
	// mediaaccountfanssnapshot.DefaultCreatedAt holds the default value on creation for the created_at field.
	mediaaccountfanssnapshot.DefaultCreatedAt = mediaaccountfanssnapshotDescCreatedAt.Default.(func() time.Time)
	// mediaaccountfanssnapshotDescUpdatedAt is the schema descriptor for updated_at field.
	mediaaccountfanssnapshotDescUpdatedAt := mediaaccountfanssnapshotMixinFields0[1].Descriptor()
	// mediaaccountfanssnapshot.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mediaaccountfanssnapshot.DefaultUpdatedAt = mediaaccountfanssnapshotDescUpdatedAt.Default.(func() time.Time)
	// mediaaccountfanssnapshot.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mediaaccountfanssnapshot.UpdateDefaultUpdatedAt = mediaaccountfanssnapshotDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mediaaccountfanssnapshotDescAccountID is the schema descriptor for account_id field.
	mediaaccountfanssnapshotDescAccountID := mediaaccountfanssnapshotFields[0].Descriptor()
	// mediaaccountfanssnapshot.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	mediaaccountfanssnapshot.AccountIDValidator = mediaaccountfanssnapshotDescAccountID.Validators[0].(func(int) error)
	// mediaaccountfanssnapshotDescFansCount is the schema descriptor for fans_count field.
	mediaaccountfanssnapshotDescFansCount := mediaaccountfanssnapshotFields[1].Descriptor()
	// mediaaccountfanssnapshot.FansCountValidator is a validator for the "fans_count" field. It is called by the builders before save.
	mediaaccountfanssnapshot.FansCountValidator = mediaaccountfanssnapshotDescFansCount.Validators[0].(func(int) error)
	// mediaaccountfanssnapshotDescSnapshotDate is the schema descriptor for snapshot_date field.
	mediaaccountfanssnapshotDescSnapshotDate := mediaaccountfanssnapshotFields[2].Descriptor()
	// mediaaccountfanssnapshot.DefaultSnapshotDate holds the default value on creation for the snapshot_date field.
	mediaaccountfanssnapshot.DefaultSnapshotDate = mediaaccountfanssnapshotDescSnapshotDate.Default.(func() time.Time)
	mediacontentMixin := schema.MediaContent{}.Mixin()
	mediacontentMixinFields0 := mediacontentMixin[0].Fields()
	_ = mediacontentMixinFields0
	mediacontentFields := schema.MediaContent{}.Fields()
	_ = mediacontentFields
	// mediacontentDescCreatedAt is the schema descriptor for created_at field.
	mediacontentDescCreatedAt := mediacontentMixinFields0[0].Descriptor()
	// mediacontent.DefaultCreatedAt holds the default value on creation for the created_at field.
	mediacontent.DefaultCreatedAt = mediacontentDescCreatedAt.Default.(func() time.Time)
	// mediacontentDescUpdatedAt is the schema descriptor for updated_at field.
	mediacontentDescUpdatedAt := mediacontentMixinFields0[1].Descriptor()
	// mediacontent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mediacontent.DefaultUpdatedAt = mediacontentDescUpdatedAt.Default.(func() time.Time)
	// mediacontent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mediacontent.UpdateDefaultUpdatedAt = mediacontentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mediacontentDescTitle is the schema descriptor for title field.
	mediacontentDescTitle := mediacontentFields[0].Descriptor()
	// mediacontent.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	mediacontent.TitleValidator = func() func(string) error {
		validators := mediacontentDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mediacontentDescCoverImage is the schema descriptor for cover_image field.
	mediacontentDescCoverImage := mediacontentFields[2].Descriptor()
	// mediacontent.CoverImageValidator is a validator for the "cover_image" field. It is called by the builders before save.
	mediacontent.CoverImageValidator = mediacontentDescCoverImage.Validators[0].(func(string) error)
	// mediacontentDescPlatform is the schema descriptor for platform field.
	mediacontentDescPlatform := mediacontentFields[3].Descriptor()
	// mediacontent.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	mediacontent.PlatformValidator = func() func(string) error {
		validators := mediacontentDescPlatform.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(platform string) error {
			for _, fn := range fns {
				if err := fn(platform); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mediacontentDescStatus is the schema descriptor for status field.
	mediacontentDescStatus := mediacontentFields[5].Descriptor()
	// mediacontent.DefaultStatus holds the default value on creation for the status field.
	mediacontent.DefaultStatus = mediacontentDescStatus.Default.(string)
	// mediacontent.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	mediacontent.StatusValidator = mediacontentDescStatus.Validators[0].(func(string) error)
	// mediacontentDescViews is the schema descriptor for views field.
	mediacontentDescViews := mediacontentFields[6].Descriptor()
	// mediacontent.DefaultViews holds the default value on creation for the views field.
	mediacontent.DefaultViews = mediacontentDescViews.Default.(int)
	// mediacontentDescLikes is the schema descriptor for likes field.
	mediacontentDescLikes := mediacontentFields[7].Descriptor()
	// mediacontent.DefaultLikes holds the default value on creation for the likes field.
	mediacontent.DefaultLikes = mediacontentDescLikes.Default.(int)
	// mediacontentDescComments is the schema descriptor for comments field.
	mediacontentDescComments := mediacontentFields[8].Descriptor()
	// mediacontent.DefaultComments holds the default value on creation for the comments field.
	mediacontent.DefaultComments = mediacontentDescComments.Default.(int)
	// mediacontentDescShares is the schema descriptor for shares field.
	mediacontentDescShares := mediacontentFields[9].Descriptor()
	// mediacontent.DefaultShares holds the default value on creation for the shares field.
	mediacontent.DefaultShares = mediacontentDescShares.Default.(int)
	mediacontentversionMixin := schema.MediaContentVersion{}.Mixin()
	mediacontentversionMixinFields0 := mediacontentversionMixin[0].Fields()
	_ = mediacontentversionMixinFields0
	mediacontentversionFields := schema.MediaContentVersion{}.Fields()
	_ = mediacontentversionFields
	// mediacontentversionDescCreatedAt is the schema descriptor for created_at field.
	mediacontentversionDescCreatedAt := mediacontentversionMixinFields0[0].Descriptor()
	// mediacontentversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	mediacontentversion.DefaultCreatedAt = mediacontentversionDescCreatedAt.Default.(func() time.Time)
	// mediacontentversionDescUpdatedAt is the schema descriptor for updated_at field.
	mediacontentversionDescUpdatedAt := mediacontentversionMixinFields0[1].Descriptor()
	// mediacontentversion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mediacontentversion.DefaultUpdatedAt = mediacontentversionDescUpdatedAt.Default.(func() time.Time)
	// mediacontentversion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mediacontentversion.UpdateDefaultUpdatedAt = mediacontentversionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mediacontentversionDescContentID is the schema descriptor for content_id field.
	mediacontentversionDescContentID := mediacontentversionFields[0].Descriptor()
	// mediacontentversion.ContentIDValidator is a validator for the "content_id" field. It is called by the builders before save.
	mediacontentversion.ContentIDValidator = mediacontentversionDescContentID.Validators[0].(func(int) error)
	// mediacontentversionDescVersionNo is the schema descriptor for version_no field.
	mediacontentversionDescVersionNo := mediacontentversionFields[1].Descriptor()
	// mediacontentversion.VersionNoValidator is a validator for the "version_no" field. It is called by the builders before save.
	mediacontentversion.VersionNoValidator = mediacontentversionDescVersionNo.Validators[0].(func(int) error)
	// mediacontentversionDescTitle is the schema descriptor for title field.
	mediacontentversionDescTitle := mediacontentversionFields[2].Descriptor()
	// mediacontentversion.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	mediacontentversion.TitleValidator = func() func(string) error {
		validators := mediacontentversionDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mediacontentversionDescCoverImage is the schema descriptor for cover_image field.
	mediacontentversionDescCoverImage := mediacontentversionFields[4].Descriptor()
	// mediacontentversion.CoverImageValidator is a validator for the "cover_image" field. It is called by the builders before save.
	mediacontentversion.CoverImageValidator = mediacontentversionDescCoverImage.Validators[0].(func(string) error)
	// mediacontentversionDescStatus is the schema descriptor for status field.
	mediacontentversionDescStatus := mediacontentversionFields[5].Descriptor()
	// mediacontentversion.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	mediacontentversion.StatusValidator = func() func(string) error {
		validators := mediacontentversionDescStatus.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(status string) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mediacontentversionDescEditReason is the schema descriptor for edit_reason field.
	mediacontentversionDescEditReason := mediacontentversionFields[7].Descriptor()
	// mediacontentversion.EditReasonValidator is a validator for the "edit_reason" field. It is called by the builders before save.
	mediacontentversion.EditReasonValidator = mediacontentversionDescEditReason.Validators[0].(func(string) error)
	newsMixin := schema.News{}.Mixin()
	newsMixinFields0 := newsMixin[0].Fields()
	_ = newsMixinFields0
	newsFields := schema.News{}.Fields()
	_ = newsFields
	// newsDescCreatedAt is the schema descriptor for created_at field.
	newsDescCreatedAt := newsMixinFields0[0].Descriptor()
	// news.DefaultCreatedAt holds the default value on creation for the created_at field.
	news.DefaultCreatedAt = newsDescCreatedAt.Default.(func() time.Time)
	// newsDescUpdatedAt is the schema descriptor for updated_at field.
	newsDescUpdatedAt := newsMixinFields0[1].Descriptor()
	// news.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	news.DefaultUpdatedAt = newsDescUpdatedAt.Default.(func() time.Time)
	// news.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	news.UpdateDefaultUpdatedAt = newsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// newsDescGroupID is the schema descriptor for group_id field.
	newsDescGroupID := newsFields[0].Descriptor()
	// news.GroupIDValidator is a validator for the "group_id" field. It is called by the builders before save.
	news.GroupIDValidator = newsDescGroupID.Validators[0].(func(int) error)
	// newsDescTitle is the schema descriptor for title field.
	newsDescTitle := newsFields[1].Descriptor()
	// news.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	news.TitleValidator = func() func(string) error {
		validators := newsDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// newsDescCreatorID is the schema descriptor for creator_id field.
	newsDescCreatorID := newsFields[3].Descriptor()
	// news.CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	news.CreatorIDValidator = newsDescCreatorID.Validators[0].(func(int) error)
	newsgroupMixin := schema.NewsGroup{}.Mixin()
	newsgroupMixinFields0 := newsgroupMixin[0].Fields()
	_ = newsgroupMixinFields0
	newsgroupFields := schema.NewsGroup{}.Fields()
	_ = newsgroupFields
	// newsgroupDescCreatedAt is the schema descriptor for created_at field.
	newsgroupDescCreatedAt := newsgroupMixinFields0[0].Descriptor()
	// newsgroup.DefaultCreatedAt holds the default value on creation for the created_at field.
	newsgroup.DefaultCreatedAt = newsgroupDescCreatedAt.Default.(func() time.Time)
	// newsgroupDescUpdatedAt is the schema descriptor for updated_at field.
	newsgroupDescUpdatedAt := newsgroupMixinFields0[1].Descriptor()
	// newsgroup.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	newsgroup.DefaultUpdatedAt = newsgroupDescUpdatedAt.Default.(func() time.Time)
	// newsgroup.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	newsgroup.UpdateDefaultUpdatedAt = newsgroupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// newsgroupDescName is the schema descriptor for name field.
	newsgroupDescName := newsgroupFields[0].Descriptor()
	// newsgroup.NameValidator is a validator for the "name" field. It is called by the builders before save.
	newsgroup.NameValidator = func() func(string) error {
		validators := newsgroupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// newsgroupDescDescription is the schema descriptor for description field.
	newsgroupDescDescription := newsgroupFields[1].Descriptor()
	// newsgroup.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	newsgroup.DescriptionValidator = newsgroupDescDescription.Validators[0].(func(string) error)
	// newsgroupDescSortOrder is the schema descriptor for sort_order field.
	newsgroupDescSortOrder := newsgroupFields[2].Descriptor()
	// newsgroup.DefaultSortOrder holds the default value on creation for the sort_order field.
	newsgroup.DefaultSortOrder = newsgroupDescSortOrder.Default.(int)
	operationlogMixin := schema.OperationLog{}.Mixin()
	operationlogMixinFields0 := operationlogMixin[0].Fields()
	_ = operationlogMixinFields0
	operationlogFields := schema.OperationLog{}.Fields()
	_ = operationlogFields
	// operationlogDescCreatedAt is the schema descriptor for created_at field.
	operationlogDescCreatedAt := operationlogMixinFields0[0].Descriptor()
	// operationlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	operationlog.DefaultCreatedAt = operationlogDescCreatedAt.Default.(func() time.Time)
	// operationlogDescUpdatedAt is the schema descriptor for updated_at field.
	operationlogDescUpdatedAt := operationlogMixinFields0[1].Descriptor()
	// operationlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	operationlog.DefaultUpdatedAt = operationlogDescUpdatedAt.Default.(func() time.Time)
	// operationlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	operationlog.UpdateDefaultUpdatedAt = operationlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// operationlogDescUsername is the schema descriptor for username field.
	operationlogDescUsername := operationlogFields[1].Descriptor()
	// operationlog.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	operationlog.UsernameValidator = operationlogDescUsername.Validators[0].(func(string) error)
	// operationlogDescOperationType is the schema descriptor for operation_type field.
	operationlogDescOperationType := operationlogFields[2].Descriptor()
	// operationlog.OperationTypeValidator is a validator for the "operation_type" field. It is called by the builders before save.
	operationlog.OperationTypeValidator = func() func(string) error {
		validators := operationlogDescOperationType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(operation_type string) error {
			for _, fn := range fns {
				if err := fn(operation_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// operationlogDescModule is the schema descriptor for module field.
	operationlogDescModule := operationlogFields[3].Descriptor()
	// operationlog.ModuleValidator is a validator for the "module" field. It is called by the builders before save.
	operationlog.ModuleValidator = func() func(string) error {
		validators := operationlogDescModule.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(module string) error {
			for _, fn := range fns {
				if err := fn(module); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// operationlogDescAction is the schema descriptor for action field.
	operationlogDescAction := operationlogFields[4].Descriptor()
	// operationlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	operationlog.ActionValidator = func() func(string) error {
		validators := operationlogDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// operationlogDescResourceType is the schema descriptor for resource_type field.
	operationlogDescResourceType := operationlogFields[5].Descriptor()
	// operationlog.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	operationlog.ResourceTypeValidator = operationlogDescResourceType.Validators[0].(func(string) error)
	// operationlogDescResourceName is the schema descriptor for resource_name field.
	operationlogDescResourceName := operationlogFields[7].Descriptor()
	// operationlog.ResourceNameValidator is a validator for the "resource_name" field. It is called by the builders before save.
	operationlog.ResourceNameValidator = operationlogDescResourceName.Validators[0].(func(string) error)
	// operationlogDescDetail is the schema descriptor for detail field.
	operationlogDescDetail := operationlogFields[9].Descriptor()
	// operationlog.DetailValidator is a validator for the "detail" field. It is called by the builders before save.
	operationlog.DetailValidator = operationlogDescDetail.Validators[0].(func(string) error)
	// operationlogDescIPAddress is the schema descriptor for ip_address field.
	operationlogDescIPAddress := operationlogFields[10].Descriptor()
	// operationlog.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	operationlog.IPAddressValidator = operationlogDescIPAddress.Validators[0].(func(string) error)
	// operationlogDescUserAgent is the schema descriptor for user_agent field.
	operationlogDescUserAgent := operationlogFields[11].Descriptor()
	// operationlog.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	operationlog.UserAgentValidator = operationlogDescUserAgent.Validators[0].(func(string) error)
	// operationlogDescStatus is the schema descriptor for status field.
	operationlogDescStatus := operationlogFields[12].Descriptor()
	// operationlog.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	operationlog.StatusValidator = func() func(string) error {
		validators := operationlogDescStatus.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(status string) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// operationlogDescErrorMessage is the schema descriptor for error_message field.
	operationlogDescErrorMessage := operationlogFields[13].Descriptor()
	// operationlog.ErrorMessageValidator is a validator for the "error_message" field. It is called by the builders before save.
	operationlog.ErrorMessageValidator = operationlogDescErrorMessage.Validators[0].(func(string) error)
	permissionMixin := schema.Permission{}.Mixin()
	permissionMixinFields0 := permissionMixin[0].Fields()
	_ = permissionMixinFields0
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionMixinFields0[0].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionMixinFields0[1].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// permissionDescName is the schema descriptor for name field.
	permissionDescName := permissionFields[1].Descriptor()
	// permission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	permission.NameValidator = func() func(string) error {
		validators := permissionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescResourceType is the schema descriptor for resource_type field.
	permissionDescResourceType := permissionFields[2].Descriptor()
	// permission.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	permission.ResourceTypeValidator = func() func(string) error {
		validators := permissionDescResourceType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_type string) error {
			for _, fn := range fns {
				if err := fn(resource_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescResourcePath is the schema descriptor for resource_path field.
	permissionDescResourcePath := permissionFields[3].Descriptor()
	// permission.ResourcePathValidator is a validator for the "resource_path" field. It is called by the builders before save.
	permission.ResourcePathValidator = func() func(string) error {
		validators := permissionDescResourcePath.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_path string) error {
			for _, fn := range fns {
				if err := fn(resource_path); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescHTTPMethod is the schema descriptor for http_method field.
	permissionDescHTTPMethod := permissionFields[4].Descriptor()
	// permission.HTTPMethodValidator is a validator for the "http_method" field. It is called by the builders before save.
	permission.HTTPMethodValidator = permissionDescHTTPMethod.Validators[0].(func(string) error)
	// permissionDescDescription is the schema descriptor for description field.
	permissionDescDescription := permissionFields[5].Descriptor()
	// permission.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	permission.DescriptionValidator = permissionDescDescription.Validators[0].(func(string) error)
	// permissionDescIsActive is the schema descriptor for is_active field.
	permissionDescIsActive := permissionFields[6].Descriptor()
	// permission.DefaultIsActive holds the default value on creation for the is_active field.
	permission.DefaultIsActive = permissionDescIsActive.Default.(bool)
	// permissionDescIsBuiltin is the schema descriptor for is_builtin field.
	permissionDescIsBuiltin := permissionFields[7].Descriptor()
	// permission.DefaultIsBuiltin holds the default value on creation for the is_builtin field.
	permission.DefaultIsBuiltin = permissionDescIsBuiltin.Default.(bool)
	projectMixin := schema.Project{}.Mixin()
	projectMixinFields0 := projectMixin[0].Fields()
	_ = projectMixinFields0
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectMixinFields0[0].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectMixinFields0[1].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectDescName is the schema descriptor for name field.
	projectDescName := projectFields[0].Descriptor()
	// project.NameValidator is a validator for the "name" field. It is called by the builders before save.
	project.NameValidator = func() func(string) error {
		validators := projectDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// projectDescProjectNo is the schema descriptor for project_no field.
	projectDescProjectNo := projectFields[1].Descriptor()
	// project.ProjectNoValidator is a validator for the "project_no" field. It is called by the builders before save.
	project.ProjectNoValidator = func() func(string) error {
		validators := projectDescProjectNo.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(project_no string) error {
			for _, fn := range fns {
				if err := fn(project_no); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// projectDescDescription is the schema descriptor for description field.
	projectDescDescription := projectFields[2].Descriptor()
	// project.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	project.DescriptionValidator = projectDescDescription.Validators[0].(func(string) error)
	// projectDescStatus is the schema descriptor for status field.
	projectDescStatus := projectFields[3].Descriptor()
	// project.DefaultStatus holds the default value on creation for the status field.
	project.DefaultStatus = projectDescStatus.Default.(string)
	// project.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	project.StatusValidator = projectDescStatus.Validators[0].(func(string) error)
	// projectDescPriority is the schema descriptor for priority field.
	projectDescPriority := projectFields[4].Descriptor()
	// project.DefaultPriority holds the default value on creation for the priority field.
	project.DefaultPriority = projectDescPriority.Default.(string)
	// project.PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	project.PriorityValidator = projectDescPriority.Validators[0].(func(string) error)
	// projectDescOwnerID is the schema descriptor for owner_id field.
	projectDescOwnerID := projectFields[9].Descriptor()
	// project.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	project.OwnerIDValidator = projectDescOwnerID.Validators[0].(func(int) error)
	projectmemberMixin := schema.ProjectMember{}.Mixin()
	projectmemberMixinFields0 := projectmemberMixin[0].Fields()
	_ = projectmemberMixinFields0
	projectmemberFields := schema.ProjectMember{}.Fields()
	_ = projectmemberFields
	// projectmemberDescCreatedAt is the schema descriptor for created_at field.
	projectmemberDescCreatedAt := projectmemberMixinFields0[0].Descriptor()
	// projectmember.DefaultCreatedAt holds the default value on creation for the created_at field.
	projectmember.DefaultCreatedAt = projectmemberDescCreatedAt.Default.(func() time.Time)
	// projectmemberDescUpdatedAt is the schema descriptor for updated_at field.
	projectmemberDescUpdatedAt := projectmemberMixinFields0[1].Descriptor()
	// projectmember.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	projectmember.DefaultUpdatedAt = projectmemberDescUpdatedAt.Default.(func() time.Time)
	// projectmember.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	projectmember.UpdateDefaultUpdatedAt = projectmemberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// projectmemberDescProjectID is the schema descriptor for project_id field.
	projectmemberDescProjectID := projectmemberFields[0].Descriptor()
	// projectmember.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	projectmember.ProjectIDValidator = projectmemberDescProjectID.Validators[0].(func(int) error)
	// projectmemberDescUserID is the schema descriptor for user_id field.
	projectmemberDescUserID := projectmemberFields[1].Descriptor()
	// projectmember.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	projectmember.UserIDValidator = projectmemberDescUserID.Validators[0].(func(int) error)
	// projectmemberDescRole is the schema descriptor for role field.
	projectmemberDescRole := projectmemberFields[2].Descriptor()
	// projectmember.DefaultRole holds the default value on creation for the role field.
	projectmember.DefaultRole = projectmemberDescRole.Default.(string)
	// projectmember.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	projectmember.RoleValidator = projectmemberDescRole.Validators[0].(func(string) error)
	// projectmemberDescJoinedAt is the schema descriptor for joined_at field.
	projectmemberDescJoinedAt := projectmemberFields[3].Descriptor()
	// projectmember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	projectmember.DefaultJoinedAt = projectmemberDescJoinedAt.Default.(func() time.Time)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[0].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescCode is the schema descriptor for code field.
	roleDescCode := roleFields[1].Descriptor()
	// role.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	role.CodeValidator = func() func(string) error {
		validators := roleDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[2].Descriptor()
	// role.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	role.DescriptionValidator = roleDescDescription.Validators[0].(func(string) error)
	// roleDescIsActive is the schema descriptor for is_active field.
	roleDescIsActive := roleFields[3].Descriptor()
	// role.DefaultIsActive holds the default value on creation for the is_active field.
	role.DefaultIsActive = roleDescIsActive.Default.(bool)
	// roleDescIsDefault is the schema descriptor for is_default field.
	roleDescIsDefault := roleFields[4].Descriptor()
	// role.DefaultIsDefault holds the default value on creation for the is_default field.
	role.DefaultIsDefault = roleDescIsDefault.Default.(bool)
	// roleDescIsBuiltin is the schema descriptor for is_builtin field.
	roleDescIsBuiltin := roleFields[5].Descriptor()
	// role.DefaultIsBuiltin holds the default value on creation for the is_builtin field.
	role.DefaultIsBuiltin = roleDescIsBuiltin.Default.(bool)
	// roleDescRoleType is the schema descriptor for role_type field.
	roleDescRoleType := roleFields[6].Descriptor()
	// role.RoleTypeValidator is a validator for the "role_type" field. It is called by the builders before save.
	role.RoleTypeValidator = roleDescRoleType.Validators[0].(func(string) error)
	rolepermMixin := schema.RolePerm{}.Mixin()
	rolepermMixinFields0 := rolepermMixin[0].Fields()
	_ = rolepermMixinFields0
	rolepermFields := schema.RolePerm{}.Fields()
	_ = rolepermFields
	// rolepermDescCreatedAt is the schema descriptor for created_at field.
	rolepermDescCreatedAt := rolepermMixinFields0[0].Descriptor()
	// roleperm.DefaultCreatedAt holds the default value on creation for the created_at field.
	roleperm.DefaultCreatedAt = rolepermDescCreatedAt.Default.(func() time.Time)
	// rolepermDescUpdatedAt is the schema descriptor for updated_at field.
	rolepermDescUpdatedAt := rolepermMixinFields0[1].Descriptor()
	// roleperm.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	roleperm.DefaultUpdatedAt = rolepermDescUpdatedAt.Default.(func() time.Time)
	// roleperm.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	roleperm.UpdateDefaultUpdatedAt = rolepermDescUpdatedAt.UpdateDefault.(func() time.Time)
	// rolepermDescRoleID is the schema descriptor for role_id field.
	rolepermDescRoleID := rolepermFields[0].Descriptor()
	// roleperm.RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	roleperm.RoleIDValidator = rolepermDescRoleID.Validators[0].(func(int) error)
	// rolepermDescPermissionID is the schema descriptor for permission_id field.
	rolepermDescPermissionID := rolepermFields[1].Descriptor()
	// roleperm.PermissionIDValidator is a validator for the "permission_id" field. It is called by the builders before save.
	roleperm.PermissionIDValidator = rolepermDescPermissionID.Validators[0].(func(int) error)
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskMixinFields0[0].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskMixinFields0[1].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// taskDescProjectID is the schema descriptor for project_id field.
	taskDescProjectID := taskFields[0].Descriptor()
	// task.ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	task.ProjectIDValidator = taskDescProjectID.Validators[0].(func(int) error)
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[2].Descriptor()
	// task.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	task.TitleValidator = func() func(string) error {
		validators := taskDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// taskDescDescription is the schema descriptor for description field.
	taskDescDescription := taskFields[3].Descriptor()
	// task.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	task.DescriptionValidator = taskDescDescription.Validators[0].(func(string) error)
	// taskDescStatus is the schema descriptor for status field.
	taskDescStatus := taskFields[4].Descriptor()
	// task.DefaultStatus holds the default value on creation for the status field.
	task.DefaultStatus = taskDescStatus.Default.(string)
	// task.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	task.StatusValidator = taskDescStatus.Validators[0].(func(string) error)
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[5].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(string)
	// task.PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	task.PriorityValidator = taskDescPriority.Validators[0].(func(string) error)
	// taskDescCreatorID is the schema descriptor for creator_id field.
	taskDescCreatorID := taskFields[7].Descriptor()
	// task.CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	task.CreatorIDValidator = taskDescCreatorID.Validators[0].(func(int) error)
	uploadfileMixin := schema.UploadFile{}.Mixin()
	uploadfileMixinFields0 := uploadfileMixin[0].Fields()
	_ = uploadfileMixinFields0
	uploadfileFields := schema.UploadFile{}.Fields()
	_ = uploadfileFields
	// uploadfileDescCreatedAt is the schema descriptor for created_at field.
	uploadfileDescCreatedAt := uploadfileMixinFields0[0].Descriptor()
	// uploadfile.DefaultCreatedAt holds the default value on creation for the created_at field.
	uploadfile.DefaultCreatedAt = uploadfileDescCreatedAt.Default.(func() time.Time)
	// uploadfileDescUpdatedAt is the schema descriptor for updated_at field.
	uploadfileDescUpdatedAt := uploadfileMixinFields0[1].Descriptor()
	// uploadfile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	uploadfile.DefaultUpdatedAt = uploadfileDescUpdatedAt.Default.(func() time.Time)
	// uploadfile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	uploadfile.UpdateDefaultUpdatedAt = uploadfileDescUpdatedAt.UpdateDefault.(func() time.Time)
	// uploadfileDescFilename is the schema descriptor for filename field.
	uploadfileDescFilename := uploadfileFields[0].Descriptor()
	// uploadfile.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	uploadfile.FilenameValidator = func() func(string) error {
		validators := uploadfileDescFilename.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(filename string) error {
			for _, fn := range fns {
				if err := fn(filename); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadfileDescOriginalFilename is the schema descriptor for original_filename field.
	uploadfileDescOriginalFilename := uploadfileFields[1].Descriptor()
	// uploadfile.OriginalFilenameValidator is a validator for the "original_filename" field. It is called by the builders before save.
	uploadfile.OriginalFilenameValidator = func() func(string) error {
		validators := uploadfileDescOriginalFilename.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(original_filename string) error {
			for _, fn := range fns {
				if err := fn(original_filename); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadfileDescFilePath is the schema descriptor for file_path field.
	uploadfileDescFilePath := uploadfileFields[2].Descriptor()
	// uploadfile.FilePathValidator is a validator for the "file_path" field. It is called by the builders before save.
	uploadfile.FilePathValidator = func() func(string) error {
		validators := uploadfileDescFilePath.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(file_path string) error {
			for _, fn := range fns {
				if err := fn(file_path); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadfileDescFileSize is the schema descriptor for file_size field.
	uploadfileDescFileSize := uploadfileFields[3].Descriptor()
	// uploadfile.FileSizeValidator is a validator for the "file_size" field. It is called by the builders before save.
	uploadfile.FileSizeValidator = uploadfileDescFileSize.Validators[0].(func(int64) error)
	// uploadfileDescMimeType is the schema descriptor for mime_type field.
	uploadfileDescMimeType := uploadfileFields[4].Descriptor()
	// uploadfile.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	uploadfile.MimeTypeValidator = func() func(string) error {
		validators := uploadfileDescMimeType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(mime_type string) error {
			for _, fn := range fns {
				if err := fn(mime_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadfileDescFileType is the schema descriptor for file_type field.
	uploadfileDescFileType := uploadfileFields[5].Descriptor()
	// uploadfile.FileTypeValidator is a validator for the "file_type" field. It is called by the builders before save.
	uploadfile.FileTypeValidator = func() func(string) error {
		validators := uploadfileDescFileType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(file_type string) error {
			for _, fn := range fns {
				if err := fn(file_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadfileDescExtension is the schema descriptor for extension field.
	uploadfileDescExtension := uploadfileFields[6].Descriptor()
	// uploadfile.ExtensionValidator is a validator for the "extension" field. It is called by the builders before save.
	uploadfile.ExtensionValidator = func() func(string) error {
		validators := uploadfileDescExtension.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(extension string) error {
			for _, fn := range fns {
				if err := fn(extension); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// uploadfileDescUploaderID is the schema descriptor for uploader_id field.
	uploadfileDescUploaderID := uploadfileFields[7].Descriptor()
	// uploadfile.UploaderIDValidator is a validator for the "uploader_id" field. It is called by the builders before save.
	uploadfile.UploaderIDValidator = uploadfileDescUploaderID.Validators[0].(func(int) error)
	// uploadfileDescPurpose is the schema descriptor for purpose field.
	uploadfileDescPurpose := uploadfileFields[8].Descriptor()
	// uploadfile.PurposeValidator is a validator for the "purpose" field. It is called by the builders before save.
	uploadfile.PurposeValidator = uploadfileDescPurpose.Validators[0].(func(string) error)
	// uploadfileDescMd5 is the schema descriptor for md5 field.
	uploadfileDescMd5 := uploadfileFields[9].Descriptor()
	// uploadfile.Md5Validator is a validator for the "md5" field. It is called by the builders before save.
	uploadfile.Md5Validator = uploadfileDescMd5.Validators[0].(func(string) error)
	// uploadfileDescReferenceCount is the schema descriptor for reference_count field.
	uploadfileDescReferenceCount := uploadfileFields[10].Descriptor()
	// uploadfile.DefaultReferenceCount holds the default value on creation for the reference_count field.
	uploadfile.DefaultReferenceCount = uploadfileDescReferenceCount.Default.(int)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
	// userDescSalt is the schema descriptor for salt field.
	userDescSalt := userFields[3].Descriptor()
	// user.SaltValidator is a validator for the "salt" field. It is called by the builders before save.
	user.SaltValidator = userDescSalt.Validators[0].(func(string) error)
	// userDescHashedPassword is the schema descriptor for hashed_password field.
	userDescHashedPassword := userFields[4].Descriptor()
	// user.HashedPasswordValidator is a validator for the "hashed_password" field. It is called by the builders before save.
	user.HashedPasswordValidator = userDescHashedPassword.Validators[0].(func(string) error)
	// userDescUserType is the schema descriptor for user_type field.
	userDescUserType := userFields[6].Descriptor()
	// user.DefaultUserType holds the default value on creation for the user_type field.
	user.DefaultUserType = userDescUserType.Default.(string)
	// user.UserTypeValidator is a validator for the "user_type" field. It is called by the builders before save.
	user.UserTypeValidator = userDescUserType.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[7].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescTokenVersion is the schema descriptor for token_version field.
	userDescTokenVersion := userFields[8].Descriptor()
	// user.DefaultTokenVersion holds the default value on creation for the token_version field.
	user.DefaultTokenVersion = userDescTokenVersion.Default.(int)
	// userDescVerificationCode is the schema descriptor for verification_code field.
	userDescVerificationCode := userFields[9].Descriptor()
	// user.VerificationCodeValidator is a validator for the "verification_code" field. It is called by the builders before save.
	user.VerificationCodeValidator = userDescVerificationCode.Validators[0].(func(string) error)
	verificationcodeMixin := schema.VerificationCode{}.Mixin()
	verificationcodeMixinFields0 := verificationcodeMixin[0].Fields()
	_ = verificationcodeMixinFields0
	verificationcodeFields := schema.VerificationCode{}.Fields()
	_ = verificationcodeFields
	// verificationcodeDescCreatedAt is the schema descriptor for created_at field.
	verificationcodeDescCreatedAt := verificationcodeMixinFields0[0].Descriptor()
	// verificationcode.DefaultCreatedAt holds the default value on creation for the created_at field.
	verificationcode.DefaultCreatedAt = verificationcodeDescCreatedAt.Default.(func() time.Time)
	// verificationcodeDescUpdatedAt is the schema descriptor for updated_at field.
	verificationcodeDescUpdatedAt := verificationcodeMixinFields0[1].Descriptor()
	// verificationcode.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	verificationcode.DefaultUpdatedAt = verificationcodeDescUpdatedAt.Default.(func() time.Time)
	// verificationcode.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	verificationcode.UpdateDefaultUpdatedAt = verificationcodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// verificationcodeDescCode is the schema descriptor for code field.
	verificationcodeDescCode := verificationcodeFields[0].Descriptor()
	// verificationcode.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	verificationcode.CodeValidator = func() func(string) error {
		validators := verificationcodeDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// verificationcodeDescTarget is the schema descriptor for target field.
	verificationcodeDescTarget := verificationcodeFields[1].Descriptor()
	// verificationcode.TargetValidator is a validator for the "target" field. It is called by the builders before save.
	verificationcode.TargetValidator = func() func(string) error {
		validators := verificationcodeDescTarget.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(target string) error {
			for _, fn := range fns {
				if err := fn(target); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// verificationcodeDescChannel is the schema descriptor for channel field.
	verificationcodeDescChannel := verificationcodeFields[2].Descriptor()
	// verificationcode.ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	verificationcode.ChannelValidator = func() func(string) error {
		validators := verificationcodeDescChannel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(channel string) error {
			for _, fn := range fns {
				if err := fn(channel); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// verificationcodeDescScene is the schema descriptor for scene field.
	verificationcodeDescScene := verificationcodeFields[3].Descriptor()
	// verificationcode.SceneValidator is a validator for the "scene" field. It is called by the builders before save.
	verificationcode.SceneValidator = func() func(string) error {
		validators := verificationcodeDescScene.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(scene string) error {
			for _, fn := range fns {
				if err := fn(scene); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// verificationcodeDescIsUsed is the schema descriptor for is_used field.
	verificationcodeDescIsUsed := verificationcodeFields[4].Descriptor()
	// verificationcode.DefaultIsUsed holds the default value on creation for the is_used field.
	verificationcode.DefaultIsUsed = verificationcodeDescIsUsed.Default.(bool)
	// verificationcodeDescAttempts is the schema descriptor for attempts field.
	verificationcodeDescAttempts := verificationcodeFields[5].Descriptor()
	// verificationcode.DefaultAttempts holds the default value on creation for the attempts field.
	verificationcode.DefaultAttempts = verificationcodeDescAttempts.Default.(int)
	// verificationcodeDescMaxAttempts is the schema descriptor for max_attempts field.
	verificationcodeDescMaxAttempts := verificationcodeFields[6].Descriptor()
	// verificationcode.DefaultMaxAttempts holds the default value on creation for the max_attempts field.
	verificationcode.DefaultMaxAttempts = verificationcodeDescMaxAttempts.Default.(int)
	// verificationcodeDescExpiresAt is the schema descriptor for expires_at field.
	verificationcodeDescExpiresAt := verificationcodeFields[7].Descriptor()
	// verificationcode.DefaultExpiresAt holds the default value on creation for the expires_at field.
	verificationcode.DefaultExpiresAt = verificationcodeDescExpiresAt.Default.(time.Time)
	// verificationcodeDescIPAddress is the schema descriptor for ip_address field.
	verificationcodeDescIPAddress := verificationcodeFields[9].Descriptor()
	// verificationcode.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	verificationcode.IPAddressValidator = verificationcodeDescIPAddress.Validators[0].(func(string) error)
	// verificationcodeDescUserAgent is the schema descriptor for user_agent field.
	verificationcodeDescUserAgent := verificationcodeFields[10].Descriptor()
	// verificationcode.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	verificationcode.UserAgentValidator = verificationcodeDescUserAgent.Validators[0].(func(string) error)
}
