// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"oa-nsdiy/backend/ent/predicate"
	"oa-nsdiy/backend/ent/project"
	"oa-nsdiy/backend/ent/task"
	"oa-nsdiy/backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TaskUpdate) SetProjectID(v int) *TaskUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableProjectID(v *int) *TaskUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *TaskUpdate) SetParentID(v int) *TaskUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableParentID(v *int) *TaskUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *TaskUpdate) AddParentID(v int) *TaskUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *TaskUpdate) ClearParentID() *TaskUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdate) SetTitle(v string) *TaskUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTitle(v *string) *TaskUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdate) SetDescription(v string) *TaskUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDescription(v *string) *TaskUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdate) ClearDescription() *TaskUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v string) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *string) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdate) SetPriority(v string) *TaskUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePriority(v *string) *TaskUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *TaskUpdate) SetAssigneeID(v int) *TaskUpdate {
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableAssigneeID(v *int) *TaskUpdate {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (_u *TaskUpdate) ClearAssigneeID() *TaskUpdate {
	_u.mutation.ClearAssigneeID()
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *TaskUpdate) SetCreatorID(v int) *TaskUpdate {
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableCreatorID(v *int) *TaskUpdate {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// SetPlannedStartDate sets the "planned_start_date" field.
func (_u *TaskUpdate) SetPlannedStartDate(v time.Time) *TaskUpdate {
	_u.mutation.SetPlannedStartDate(v)
	return _u
}

// SetNillablePlannedStartDate sets the "planned_start_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePlannedStartDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetPlannedStartDate(*v)
	}
	return _u
}

// ClearPlannedStartDate clears the value of the "planned_start_date" field.
func (_u *TaskUpdate) ClearPlannedStartDate() *TaskUpdate {
	_u.mutation.ClearPlannedStartDate()
	return _u
}

// SetPlannedEndDate sets the "planned_end_date" field.
func (_u *TaskUpdate) SetPlannedEndDate(v time.Time) *TaskUpdate {
	_u.mutation.SetPlannedEndDate(v)
	return _u
}

// SetNillablePlannedEndDate sets the "planned_end_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePlannedEndDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetPlannedEndDate(*v)
	}
	return _u
}

// ClearPlannedEndDate clears the value of the "planned_end_date" field.
func (_u *TaskUpdate) ClearPlannedEndDate() *TaskUpdate {
	_u.mutation.ClearPlannedEndDate()
	return _u
}

// SetActualStartTime sets the "actual_start_time" field.
func (_u *TaskUpdate) SetActualStartTime(v time.Time) *TaskUpdate {
	_u.mutation.SetActualStartTime(v)
	return _u
}

// SetNillableActualStartTime sets the "actual_start_time" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableActualStartTime(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetActualStartTime(*v)
	}
	return _u
}

// ClearActualStartTime clears the value of the "actual_start_time" field.
func (_u *TaskUpdate) ClearActualStartTime() *TaskUpdate {
	_u.mutation.ClearActualStartTime()
	return _u
}

// SetActualEndTime sets the "actual_end_time" field.
func (_u *TaskUpdate) SetActualEndTime(v time.Time) *TaskUpdate {
	_u.mutation.SetActualEndTime(v)
	return _u
}

// SetNillableActualEndTime sets the "actual_end_time" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableActualEndTime(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetActualEndTime(*v)
	}
	return _u
}

// ClearActualEndTime clears the value of the "actual_end_time" field.
func (_u *TaskUpdate) ClearActualEndTime() *TaskUpdate {
	_u.mutation.ClearActualEndTime()
	return _u
}

// SetEstimatedHours sets the "estimated_hours" field.
func (_u *TaskUpdate) SetEstimatedHours(v float64) *TaskUpdate {
	_u.mutation.ResetEstimatedHours()
	_u.mutation.SetEstimatedHours(v)
	return _u
}

// SetNillableEstimatedHours sets the "estimated_hours" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableEstimatedHours(v *float64) *TaskUpdate {
	if v != nil {
		_u.SetEstimatedHours(*v)
	}
	return _u
}

// AddEstimatedHours adds value to the "estimated_hours" field.
func (_u *TaskUpdate) AddEstimatedHours(v float64) *TaskUpdate {
	_u.mutation.AddEstimatedHours(v)
	return _u
}

// ClearEstimatedHours clears the value of the "estimated_hours" field.
func (_u *TaskUpdate) ClearEstimatedHours() *TaskUpdate {
	_u.mutation.ClearEstimatedHours()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TaskUpdate) SetProject(v *Project) *TaskUpdate {
	return _u.SetProjectID(v.ID)
}

// SetAssignee sets the "assignee" edge to the User entity.
func (_u *TaskUpdate) SetAssignee(v *User) *TaskUpdate {
	return _u.SetAssigneeID(v.ID)
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TaskUpdate) SetCreator(v *User) *TaskUpdate {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TaskUpdate) ClearProject() *TaskUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearAssignee clears the "assignee" edge to the User entity.
func (_u *TaskUpdate) ClearAssignee() *TaskUpdate {
	_u.mutation.ClearAssignee()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TaskUpdate) ClearCreator() *TaskUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := task.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Task.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := task.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Task.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := task.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Task.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorID(); ok {
		if err := task.CreatorIDValidator(v); err != nil {
			return &ValidationError{Name: "creator_id", err: fmt.Errorf(`ent: validator failed for field "Task.creator_id": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.project"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.creator"`)
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(task.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(task.FieldParentID, field.TypeInt, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(task.FieldParentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlannedStartDate(); ok {
		_spec.SetField(task.FieldPlannedStartDate, field.TypeTime, value)
	}
	if _u.mutation.PlannedStartDateCleared() {
		_spec.ClearField(task.FieldPlannedStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.PlannedEndDate(); ok {
		_spec.SetField(task.FieldPlannedEndDate, field.TypeTime, value)
	}
	if _u.mutation.PlannedEndDateCleared() {
		_spec.ClearField(task.FieldPlannedEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualStartTime(); ok {
		_spec.SetField(task.FieldActualStartTime, field.TypeTime, value)
	}
	if _u.mutation.ActualStartTimeCleared() {
		_spec.ClearField(task.FieldActualStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualEndTime(); ok {
		_spec.SetField(task.FieldActualEndTime, field.TypeTime, value)
	}
	if _u.mutation.ActualEndTimeCleared() {
		_spec.ClearField(task.FieldActualEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EstimatedHours(); ok {
		_spec.SetField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHours(); ok {
		_spec.AddField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if _u.mutation.EstimatedHoursCleared() {
		_spec.ClearField(task.FieldEstimatedHours, field.TypeFloat64)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssigneeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.AssigneeTable,
			Columns: []string{task.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssigneeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.AssigneeTable,
			Columns: []string{task.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CreatorTable,
			Columns: []string{task.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CreatorTable,
			Columns: []string{task.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TaskUpdateOne) SetProjectID(v int) *TaskUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableProjectID(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *TaskUpdateOne) SetParentID(v int) *TaskUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableParentID(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *TaskUpdateOne) AddParentID(v int) *TaskUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *TaskUpdateOne) ClearParentID() *TaskUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdateOne) SetTitle(v string) *TaskUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTitle(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdateOne) SetDescription(v string) *TaskUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDescription(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdateOne) ClearDescription() *TaskUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v string) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdateOne) SetPriority(v string) *TaskUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePriority(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *TaskUpdateOne) SetAssigneeID(v int) *TaskUpdateOne {
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableAssigneeID(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (_u *TaskUpdateOne) ClearAssigneeID() *TaskUpdateOne {
	_u.mutation.ClearAssigneeID()
	return _u
}

// SetCreatorID sets the "creator_id" field.
func (_u *TaskUpdateOne) SetCreatorID(v int) *TaskUpdateOne {
	_u.mutation.SetCreatorID(v)
	return _u
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableCreatorID(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetCreatorID(*v)
	}
	return _u
}

// SetPlannedStartDate sets the "planned_start_date" field.
func (_u *TaskUpdateOne) SetPlannedStartDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetPlannedStartDate(v)
	return _u
}

// SetNillablePlannedStartDate sets the "planned_start_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePlannedStartDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetPlannedStartDate(*v)
	}
	return _u
}

// ClearPlannedStartDate clears the value of the "planned_start_date" field.
func (_u *TaskUpdateOne) ClearPlannedStartDate() *TaskUpdateOne {
	_u.mutation.ClearPlannedStartDate()
	return _u
}

// SetPlannedEndDate sets the "planned_end_date" field.
func (_u *TaskUpdateOne) SetPlannedEndDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetPlannedEndDate(v)
	return _u
}

// SetNillablePlannedEndDate sets the "planned_end_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePlannedEndDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetPlannedEndDate(*v)
	}
	return _u
}

// ClearPlannedEndDate clears the value of the "planned_end_date" field.
func (_u *TaskUpdateOne) ClearPlannedEndDate() *TaskUpdateOne {
	_u.mutation.ClearPlannedEndDate()
	return _u
}

// SetActualStartTime sets the "actual_start_time" field.
func (_u *TaskUpdateOne) SetActualStartTime(v time.Time) *TaskUpdateOne {
	_u.mutation.SetActualStartTime(v)
	return _u
}

// SetNillableActualStartTime sets the "actual_start_time" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableActualStartTime(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetActualStartTime(*v)
	}
	return _u
}

// ClearActualStartTime clears the value of the "actual_start_time" field.
func (_u *TaskUpdateOne) ClearActualStartTime() *TaskUpdateOne {
	_u.mutation.ClearActualStartTime()
	return _u
}

// SetActualEndTime sets the "actual_end_time" field.
func (_u *TaskUpdateOne) SetActualEndTime(v time.Time) *TaskUpdateOne {
	_u.mutation.SetActualEndTime(v)
	return _u
}

// SetNillableActualEndTime sets the "actual_end_time" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableActualEndTime(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetActualEndTime(*v)
	}
	return _u
}

// ClearActualEndTime clears the value of the "actual_end_time" field.
func (_u *TaskUpdateOne) ClearActualEndTime() *TaskUpdateOne {
	_u.mutation.ClearActualEndTime()
	return _u
}

// SetEstimatedHours sets the "estimated_hours" field.
func (_u *TaskUpdateOne) SetEstimatedHours(v float64) *TaskUpdateOne {
	_u.mutation.ResetEstimatedHours()
	_u.mutation.SetEstimatedHours(v)
	return _u
}

// SetNillableEstimatedHours sets the "estimated_hours" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableEstimatedHours(v *float64) *TaskUpdateOne {
	if v != nil {
		_u.SetEstimatedHours(*v)
	}
	return _u
}

// AddEstimatedHours adds value to the "estimated_hours" field.
func (_u *TaskUpdateOne) AddEstimatedHours(v float64) *TaskUpdateOne {
	_u.mutation.AddEstimatedHours(v)
	return _u
}

// ClearEstimatedHours clears the value of the "estimated_hours" field.
func (_u *TaskUpdateOne) ClearEstimatedHours() *TaskUpdateOne {
	_u.mutation.ClearEstimatedHours()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TaskUpdateOne) SetProject(v *Project) *TaskUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetAssignee sets the "assignee" edge to the User entity.
func (_u *TaskUpdateOne) SetAssignee(v *User) *TaskUpdateOne {
	return _u.SetAssigneeID(v.ID)
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *TaskUpdateOne) SetCreator(v *User) *TaskUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TaskUpdateOne) ClearProject() *TaskUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearAssignee clears the "assignee" edge to the User entity.
func (_u *TaskUpdateOne) ClearAssignee() *TaskUpdateOne {
	_u.mutation.ClearAssignee()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *TaskUpdateOne) ClearCreator() *TaskUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.ProjectID(); ok {
		if err := task.ProjectIDValidator(v); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`ent: validator failed for field "Task.project_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := task.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Task.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := task.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Task.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := task.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Task.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatorID(); ok {
		if err := task.CreatorIDValidator(v); err != nil {
			return &ValidationError{Name: "creator_id", err: fmt.Errorf(`ent: validator failed for field "Task.creator_id": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.project"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.creator"`)
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(task.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(task.FieldParentID, field.TypeInt, value)
	}
	if _u.mutation.ParentIDCleared() {
		_spec.ClearField(task.FieldParentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlannedStartDate(); ok {
		_spec.SetField(task.FieldPlannedStartDate, field.TypeTime, value)
	}
	if _u.mutation.PlannedStartDateCleared() {
		_spec.ClearField(task.FieldPlannedStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.PlannedEndDate(); ok {
		_spec.SetField(task.FieldPlannedEndDate, field.TypeTime, value)
	}
	if _u.mutation.PlannedEndDateCleared() {
		_spec.ClearField(task.FieldPlannedEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualStartTime(); ok {
		_spec.SetField(task.FieldActualStartTime, field.TypeTime, value)
	}
	if _u.mutation.ActualStartTimeCleared() {
		_spec.ClearField(task.FieldActualStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.ActualEndTime(); ok {
		_spec.SetField(task.FieldActualEndTime, field.TypeTime, value)
	}
	if _u.mutation.ActualEndTimeCleared() {
		_spec.ClearField(task.FieldActualEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EstimatedHours(); ok {
		_spec.SetField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHours(); ok {
		_spec.AddField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if _u.mutation.EstimatedHoursCleared() {
		_spec.ClearField(task.FieldEstimatedHours, field.TypeFloat64)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssigneeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.AssigneeTable,
			Columns: []string{task.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssigneeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.AssigneeTable,
			Columns: []string{task.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CreatorTable,
			Columns: []string{task.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.CreatorTable,
			Columns: []string{task.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
