// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"oa-nsdiy/backend/ent/uploadfile"
	"oa-nsdiy/backend/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UploadFile is the model entity for the UploadFile schema.
type UploadFile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Filename holds the value of the "filename" field.
	Filename string `json:"filename,omitempty"`
	// OriginalFilename holds the value of the "original_filename" field.
	OriginalFilename string `json:"original_filename,omitempty"`
	// FilePath holds the value of the "file_path" field.
	FilePath string `json:"file_path,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize int64 `json:"file_size,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// FileType holds the value of the "file_type" field.
	FileType string `json:"file_type,omitempty"`
	// Extension holds the value of the "extension" field.
	Extension string `json:"extension,omitempty"`
	// UploaderID holds the value of the "uploader_id" field.
	UploaderID int `json:"uploader_id,omitempty"`
	// Purpose holds the value of the "purpose" field.
	Purpose string `json:"purpose,omitempty"`
	// Md5 holds the value of the "md5" field.
	Md5 string `json:"md5,omitempty"`
	// ReferenceCount holds the value of the "reference_count" field.
	ReferenceCount int `json:"reference_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UploadFileQuery when eager-loading is set.
	Edges        UploadFileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UploadFileEdges holds the relations/edges for other nodes in the graph.
type UploadFileEdges struct {
	// Uploader holds the value of the uploader edge.
	Uploader *User `json:"uploader,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UploaderOrErr returns the Uploader value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UploadFileEdges) UploaderOrErr() (*User, error) {
	if e.Uploader != nil {
		return e.Uploader, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "uploader"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UploadFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uploadfile.FieldID, uploadfile.FieldFileSize, uploadfile.FieldUploaderID, uploadfile.FieldReferenceCount:
			values[i] = new(sql.NullInt64)
		case uploadfile.FieldFilename, uploadfile.FieldOriginalFilename, uploadfile.FieldFilePath, uploadfile.FieldMimeType, uploadfile.FieldFileType, uploadfile.FieldExtension, uploadfile.FieldPurpose, uploadfile.FieldMd5:
			values[i] = new(sql.NullString)
		case uploadfile.FieldCreatedAt, uploadfile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UploadFile fields.
func (_m *UploadFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uploadfile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case uploadfile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case uploadfile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case uploadfile.FieldFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field filename", values[i])
			} else if value.Valid {
				_m.Filename = value.String
			}
		case uploadfile.FieldOriginalFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_filename", values[i])
			} else if value.Valid {
				_m.OriginalFilename = value.String
			}
		case uploadfile.FieldFilePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_path", values[i])
			} else if value.Valid {
				_m.FilePath = value.String
			}
		case uploadfile.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case uploadfile.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case uploadfile.FieldFileType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_type", values[i])
			} else if value.Valid {
				_m.FileType = value.String
			}
		case uploadfile.FieldExtension:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extension", values[i])
			} else if value.Valid {
				_m.Extension = value.String
			}
		case uploadfile.FieldUploaderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uploader_id", values[i])
			} else if value.Valid {
				_m.UploaderID = int(value.Int64)
			}
		case uploadfile.FieldPurpose:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purpose", values[i])
			} else if value.Valid {
				_m.Purpose = value.String
			}
		case uploadfile.FieldMd5:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field md5", values[i])
			} else if value.Valid {
				_m.Md5 = value.String
			}
		case uploadfile.FieldReferenceCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reference_count", values[i])
			} else if value.Valid {
				_m.ReferenceCount = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UploadFile.
// This includes values selected through modifiers, order, etc.
func (_m *UploadFile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUploader queries the "uploader" edge of the UploadFile entity.
func (_m *UploadFile) QueryUploader() *UserQuery {
	return NewUploadFileClient(_m.config).QueryUploader(_m)
}

// Update returns a builder for updating this UploadFile.
// Note that you need to call UploadFile.Unwrap() before calling this method if this UploadFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UploadFile) Update() *UploadFileUpdateOne {
	return NewUploadFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UploadFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UploadFile) Unwrap() *UploadFile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UploadFile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UploadFile) String() string {
	var builder strings.Builder
	builder.WriteString("UploadFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("filename=")
	builder.WriteString(_m.Filename)
	builder.WriteString(", ")
	builder.WriteString("original_filename=")
	builder.WriteString(_m.OriginalFilename)
	builder.WriteString(", ")
	builder.WriteString("file_path=")
	builder.WriteString(_m.FilePath)
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("file_type=")
	builder.WriteString(_m.FileType)
	builder.WriteString(", ")
	builder.WriteString("extension=")
	builder.WriteString(_m.Extension)
	builder.WriteString(", ")
	builder.WriteString("uploader_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UploaderID))
	builder.WriteString(", ")
	builder.WriteString("purpose=")
	builder.WriteString(_m.Purpose)
	builder.WriteString(", ")
	builder.WriteString("md5=")
	builder.WriteString(_m.Md5)
	builder.WriteString(", ")
	builder.WriteString("reference_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferenceCount))
	builder.WriteByte(')')
	return builder.String()
}

// UploadFiles is a parsable slice of UploadFile.
type UploadFiles []*UploadFile
