// Code generated by ent, DO NOT EDIT.

package mediacontentversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the mediacontentversion type in the database.
	Label = "media_content_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldContentID holds the string denoting the content_id field in the database.
	FieldContentID = "content_id"
	// FieldVersionNo holds the string denoting the version_no field in the database.
	FieldVersionNo = "version_no"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCoverImage holds the string denoting the cover_image field in the database.
	FieldCoverImage = "cover_image"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldEditorID holds the string denoting the editor_id field in the database.
	FieldEditorID = "editor_id"
	// FieldEditReason holds the string denoting the edit_reason field in the database.
	FieldEditReason = "edit_reason"
	// EdgeMediaContent holds the string denoting the media_content edge name in mutations.
	EdgeMediaContent = "media_content"
	// EdgeEditor holds the string denoting the editor edge name in mutations.
	EdgeEditor = "editor"
	// Table holds the table name of the mediacontentversion in the database.
	Table = "media_content_versions"
	// MediaContentTable is the table that holds the media_content relation/edge.
	MediaContentTable = "media_content_versions"
	// MediaContentInverseTable is the table name for the MediaContent entity.
	// It exists in this package in order to avoid circular dependency with the "mediacontent" package.
	MediaContentInverseTable = "media_contents"
	// MediaContentColumn is the table column denoting the media_content relation/edge.
	MediaContentColumn = "content_id"
	// EditorTable is the table that holds the editor relation/edge.
	EditorTable = "media_content_versions"
	// EditorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	EditorInverseTable = "users"
	// EditorColumn is the table column denoting the editor relation/edge.
	EditorColumn = "editor_id"
)

// Columns holds all SQL columns for mediacontentversion fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldContentID,
	FieldVersionNo,
	FieldTitle,
	FieldContent,
	FieldCoverImage,
	FieldStatus,
	FieldEditorID,
	FieldEditReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ContentIDValidator is a validator for the "content_id" field. It is called by the builders before save.
	ContentIDValidator func(int) error
	// VersionNoValidator is a validator for the "version_no" field. It is called by the builders before save.
	VersionNoValidator func(int) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// CoverImageValidator is a validator for the "cover_image" field. It is called by the builders before save.
	CoverImageValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// EditReasonValidator is a validator for the "edit_reason" field. It is called by the builders before save.
	EditReasonValidator func(string) error
)

// OrderOption defines the ordering options for the MediaContentVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByContentID orders the results by the content_id field.
func ByContentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentID, opts...).ToFunc()
}

// ByVersionNo orders the results by the version_no field.
func ByVersionNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionNo, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCoverImage orders the results by the cover_image field.
func ByCoverImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverImage, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByEditorID orders the results by the editor_id field.
func ByEditorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEditorID, opts...).ToFunc()
}

// ByEditReason orders the results by the edit_reason field.
func ByEditReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEditReason, opts...).ToFunc()
}

// ByMediaContentField orders the results by media_content field.
func ByMediaContentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMediaContentStep(), sql.OrderByField(field, opts...))
	}
}

// ByEditorField orders the results by editor field.
func ByEditorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEditorStep(), sql.OrderByField(field, opts...))
	}
}
func newMediaContentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MediaContentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MediaContentTable, MediaContentColumn),
	)
}
func newEditorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EditorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EditorTable, EditorColumn),
	)
}
