// Code generated by ent, DO NOT EDIT.

package task

import (
	"oa-nsdiy/backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProjectID, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldParentID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStatus, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPriority, v))
}

// AssigneeID applies equality check predicate on the "assignee_id" field. It's identical to AssigneeIDEQ.
func AssigneeID(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssigneeID, v))
}

// CreatorID applies equality check predicate on the "creator_id" field. It's identical to CreatorIDEQ.
func CreatorID(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatorID, v))
}

// PlannedStartDate applies equality check predicate on the "planned_start_date" field. It's identical to PlannedStartDateEQ.
func PlannedStartDate(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPlannedStartDate, v))
}

// PlannedEndDate applies equality check predicate on the "planned_end_date" field. It's identical to PlannedEndDateEQ.
func PlannedEndDate(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPlannedEndDate, v))
}

// ActualStartTime applies equality check predicate on the "actual_start_time" field. It's identical to ActualStartTimeEQ.
func ActualStartTime(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldActualStartTime, v))
}

// ActualEndTime applies equality check predicate on the "actual_end_time" field. It's identical to ActualEndTimeEQ.
func ActualEndTime(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldActualEndTime, v))
}

// EstimatedHours applies equality check predicate on the "estimated_hours" field. It's identical to EstimatedHoursEQ.
func EstimatedHours(v float64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldEstimatedHours, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldProjectID, vs...))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldParentID, v))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldParentID))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldStatus, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldPriority, v))
}

// PriorityContains applies the Contains predicate on the "priority" field.
func PriorityContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldPriority, v))
}

// PriorityHasPrefix applies the HasPrefix predicate on the "priority" field.
func PriorityHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldPriority, v))
}

// PriorityHasSuffix applies the HasSuffix predicate on the "priority" field.
func PriorityHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldPriority, v))
}

// PriorityEqualFold applies the EqualFold predicate on the "priority" field.
func PriorityEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldPriority, v))
}

// PriorityContainsFold applies the ContainsFold predicate on the "priority" field.
func PriorityContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldPriority, v))
}

// AssigneeIDEQ applies the EQ predicate on the "assignee_id" field.
func AssigneeIDEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssigneeID, v))
}

// AssigneeIDNEQ applies the NEQ predicate on the "assignee_id" field.
func AssigneeIDNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldAssigneeID, v))
}

// AssigneeIDIn applies the In predicate on the "assignee_id" field.
func AssigneeIDIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldAssigneeID, vs...))
}

// AssigneeIDNotIn applies the NotIn predicate on the "assignee_id" field.
func AssigneeIDNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldAssigneeID, vs...))
}

// AssigneeIDIsNil applies the IsNil predicate on the "assignee_id" field.
func AssigneeIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldAssigneeID))
}

// AssigneeIDNotNil applies the NotNil predicate on the "assignee_id" field.
func AssigneeIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldAssigneeID))
}

// CreatorIDEQ applies the EQ predicate on the "creator_id" field.
func CreatorIDEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatorID, v))
}

// CreatorIDNEQ applies the NEQ predicate on the "creator_id" field.
func CreatorIDNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCreatorID, v))
}

// CreatorIDIn applies the In predicate on the "creator_id" field.
func CreatorIDIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCreatorID, vs...))
}

// CreatorIDNotIn applies the NotIn predicate on the "creator_id" field.
func CreatorIDNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCreatorID, vs...))
}

// PlannedStartDateEQ applies the EQ predicate on the "planned_start_date" field.
func PlannedStartDateEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPlannedStartDate, v))
}

// PlannedStartDateNEQ applies the NEQ predicate on the "planned_start_date" field.
func PlannedStartDateNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPlannedStartDate, v))
}

// PlannedStartDateIn applies the In predicate on the "planned_start_date" field.
func PlannedStartDateIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPlannedStartDate, vs...))
}

// PlannedStartDateNotIn applies the NotIn predicate on the "planned_start_date" field.
func PlannedStartDateNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPlannedStartDate, vs...))
}

// PlannedStartDateGT applies the GT predicate on the "planned_start_date" field.
func PlannedStartDateGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldPlannedStartDate, v))
}

// PlannedStartDateGTE applies the GTE predicate on the "planned_start_date" field.
func PlannedStartDateGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldPlannedStartDate, v))
}

// PlannedStartDateLT applies the LT predicate on the "planned_start_date" field.
func PlannedStartDateLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldPlannedStartDate, v))
}

// PlannedStartDateLTE applies the LTE predicate on the "planned_start_date" field.
func PlannedStartDateLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldPlannedStartDate, v))
}

// PlannedStartDateIsNil applies the IsNil predicate on the "planned_start_date" field.
func PlannedStartDateIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldPlannedStartDate))
}

// PlannedStartDateNotNil applies the NotNil predicate on the "planned_start_date" field.
func PlannedStartDateNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldPlannedStartDate))
}

// PlannedEndDateEQ applies the EQ predicate on the "planned_end_date" field.
func PlannedEndDateEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPlannedEndDate, v))
}

// PlannedEndDateNEQ applies the NEQ predicate on the "planned_end_date" field.
func PlannedEndDateNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPlannedEndDate, v))
}

// PlannedEndDateIn applies the In predicate on the "planned_end_date" field.
func PlannedEndDateIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPlannedEndDate, vs...))
}

// PlannedEndDateNotIn applies the NotIn predicate on the "planned_end_date" field.
func PlannedEndDateNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPlannedEndDate, vs...))
}

// PlannedEndDateGT applies the GT predicate on the "planned_end_date" field.
func PlannedEndDateGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldPlannedEndDate, v))
}

// PlannedEndDateGTE applies the GTE predicate on the "planned_end_date" field.
func PlannedEndDateGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldPlannedEndDate, v))
}

// PlannedEndDateLT applies the LT predicate on the "planned_end_date" field.
func PlannedEndDateLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldPlannedEndDate, v))
}

// PlannedEndDateLTE applies the LTE predicate on the "planned_end_date" field.
func PlannedEndDateLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldPlannedEndDate, v))
}

// PlannedEndDateIsNil applies the IsNil predicate on the "planned_end_date" field.
func PlannedEndDateIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldPlannedEndDate))
}

// PlannedEndDateNotNil applies the NotNil predicate on the "planned_end_date" field.
func PlannedEndDateNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldPlannedEndDate))
}

// ActualStartTimeEQ applies the EQ predicate on the "actual_start_time" field.
func ActualStartTimeEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldActualStartTime, v))
}

// ActualStartTimeNEQ applies the NEQ predicate on the "actual_start_time" field.
func ActualStartTimeNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldActualStartTime, v))
}

// ActualStartTimeIn applies the In predicate on the "actual_start_time" field.
func ActualStartTimeIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldActualStartTime, vs...))
}

// ActualStartTimeNotIn applies the NotIn predicate on the "actual_start_time" field.
func ActualStartTimeNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldActualStartTime, vs...))
}

// ActualStartTimeGT applies the GT predicate on the "actual_start_time" field.
func ActualStartTimeGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldActualStartTime, v))
}

// ActualStartTimeGTE applies the GTE predicate on the "actual_start_time" field.
func ActualStartTimeGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldActualStartTime, v))
}

// ActualStartTimeLT applies the LT predicate on the "actual_start_time" field.
func ActualStartTimeLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldActualStartTime, v))
}

// ActualStartTimeLTE applies the LTE predicate on the "actual_start_time" field.
func ActualStartTimeLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldActualStartTime, v))
}

// ActualStartTimeIsNil applies the IsNil predicate on the "actual_start_time" field.
func ActualStartTimeIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldActualStartTime))
}

// ActualStartTimeNotNil applies the NotNil predicate on the "actual_start_time" field.
func ActualStartTimeNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldActualStartTime))
}

// ActualEndTimeEQ applies the EQ predicate on the "actual_end_time" field.
func ActualEndTimeEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldActualEndTime, v))
}

// ActualEndTimeNEQ applies the NEQ predicate on the "actual_end_time" field.
func ActualEndTimeNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldActualEndTime, v))
}

// ActualEndTimeIn applies the In predicate on the "actual_end_time" field.
func ActualEndTimeIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldActualEndTime, vs...))
}

// ActualEndTimeNotIn applies the NotIn predicate on the "actual_end_time" field.
func ActualEndTimeNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldActualEndTime, vs...))
}

// ActualEndTimeGT applies the GT predicate on the "actual_end_time" field.
func ActualEndTimeGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldActualEndTime, v))
}

// ActualEndTimeGTE applies the GTE predicate on the "actual_end_time" field.
func ActualEndTimeGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldActualEndTime, v))
}

// ActualEndTimeLT applies the LT predicate on the "actual_end_time" field.
func ActualEndTimeLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldActualEndTime, v))
}

// ActualEndTimeLTE applies the LTE predicate on the "actual_end_time" field.
func ActualEndTimeLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldActualEndTime, v))
}

// ActualEndTimeIsNil applies the IsNil predicate on the "actual_end_time" field.
func ActualEndTimeIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldActualEndTime))
}

// ActualEndTimeNotNil applies the NotNil predicate on the "actual_end_time" field.
func ActualEndTimeNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldActualEndTime))
}

// EstimatedHoursEQ applies the EQ predicate on the "estimated_hours" field.
func EstimatedHoursEQ(v float64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldEstimatedHours, v))
}

// EstimatedHoursNEQ applies the NEQ predicate on the "estimated_hours" field.
func EstimatedHoursNEQ(v float64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldEstimatedHours, v))
}

// EstimatedHoursIn applies the In predicate on the "estimated_hours" field.
func EstimatedHoursIn(vs ...float64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldEstimatedHours, vs...))
}

// EstimatedHoursNotIn applies the NotIn predicate on the "estimated_hours" field.
func EstimatedHoursNotIn(vs ...float64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldEstimatedHours, vs...))
}

// EstimatedHoursGT applies the GT predicate on the "estimated_hours" field.
func EstimatedHoursGT(v float64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldEstimatedHours, v))
}

// EstimatedHoursGTE applies the GTE predicate on the "estimated_hours" field.
func EstimatedHoursGTE(v float64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldEstimatedHours, v))
}

// EstimatedHoursLT applies the LT predicate on the "estimated_hours" field.
func EstimatedHoursLT(v float64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldEstimatedHours, v))
}

// EstimatedHoursLTE applies the LTE predicate on the "estimated_hours" field.
func EstimatedHoursLTE(v float64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldEstimatedHours, v))
}

// EstimatedHoursIsNil applies the IsNil predicate on the "estimated_hours" field.
func EstimatedHoursIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldEstimatedHours))
}

// EstimatedHoursNotNil applies the NotNil predicate on the "estimated_hours" field.
func EstimatedHoursNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldEstimatedHours))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignee applies the HasEdge predicate on the "assignee" edge.
func HasAssignee() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssigneeTable, AssigneeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssigneeWith applies the HasEdge predicate on the "assignee" edge with a given conditions (other predicates).
func HasAssigneeWith(preds ...predicate.User) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newAssigneeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Task) predicate.Task {
	return predicate.Task(sql.NotPredicates(p))
}
