version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: manual
  push:
    branches:
      include:
        - master
stages:
  - name: build
    displayName: 构建前端和后端
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_frontend
        displayName: 构建前端
        nodeVersion: 22.22.0
        commands:
          - npm config set registry https://registry.npmmirror.com
          - cd frontend
          - npm install && npm run build
        artifacts:
          - name: FRONTEND_ARTIFACT
            path:
              - frontend/out
        caches:
          - ~/.npm
        notify: []
        strategy:
          retry: '0'
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: '1.24'
        commands:
          - '# 默认使用goproxy.cn'
          - export GOPROXY=https://goproxy.cn
          - '# 输入你的构建命令'
          - make build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./output
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_frontend
      - step: build@golang
        name: build_backend
        displayName: 构建后端
        golangVersion: '1.24'
        commands:
          - export GOPROXY=https://goproxy.cn
          - ls -la frontend/out/
          - mkdir -p backend/internal/web/dist
          - cp -r frontend/out/* backend/internal/web/dist/
          - ls -la backend/internal/web/dist/
          - cd backend
          - CGO_ENABLED=0 go build -tags embed -ldflags="-s -w" -o bin/server ./cmd/server
        artifacts:
          - name: BACKEND_ARTIFACT
            path:
              - ./bin
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: '0'
  - name: publish
    displayName: 上传制品
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_backend
        displayName: 上传后端制品
        dependArtifact: BACKEND_ARTIFACT
        artifactName: backend
        notify: []
        strategy:
          retry: '0'
